import type {CityEvent} from './types';
const checkedAt='2026-09-09T09:00:00Z';
const base={checkedAt,status:'scheduled',price:'unknown',bookingUrl:null,endTime:null,family:null,indoor:null} as const;
/** Explicit dated announcements, checked against the issuing institution. No synthetic events. */
export const eventSnapshot:CityEvent[]=[
 ...['11','18','25'].map(day=>({...base,id:`ebb-yesilcam-2026-09-${day}`,title:'Yeşilçam Geceleri · Sandalyeni Kap Gel',category:'cinema' as const,district:'Tepebaşı' as const,date:`2026-09-${day}`,time:'20:00',venue:'Aktif Yaşam Parkı',venueId:'aktif-yasam',organizer:'Eskişehir Büyükşehir Belediyesi · Belkent A.Ş.',sourceId:'ebb',sourceUrl:'https://www.eskisehir.bel.tr/icerik-detay.php?cat_icerik=1&icerik_id=13262&menu_id=24',summary:'Açık hava sinema buluşması. Film adı ve bitiş saati duyuruda belirtilmiyor; sandalyenizi yanınıza alabilirsiniz.',family:true,indoor:false})),
 {...base,id:'ebb-ekonomi-2026-09-26',title:'2026 Eskişehir Yılında Ekonominin Rotası',category:'talk',district:'Odunpazarı',date:'2026-09-26',time:'19:00',venue:'Atatürk Kültür, Sanat ve Kongre Merkezi',venueId:'ataturk-kongre',organizer:'Eskişehir Büyükşehir Belediyesi · ESMİAD',sourceId:'ebb',sourceUrl:'https://www.eskisehir.bel.tr/icerik-detay.php?cat_icerik=1&icerik_id=13265&menu_id=24',summary:'Ekonomi ve kent potansiyeli üzerine halka yönelik söyleşi. Bitiş saati ve giriş koşulları için kurum duyurusunu kontrol edin.',indoor:true},
 {...base,id:'tepebasi-nostaljik-futbol-2026-09-14',title:'Mahalleler Arası Nostaljik Futbol Turnuvası',category:'sport',district:'Tepebaşı',date:'2026-09-14',time:'18:30',venue:'Tepebaşı Belediyesi Futbol Sahası',venueId:null,organizer:'Tepebaşı Belediyesi',sourceId:'tepebasi',sourceUrl:'https://www.tepebasi.bel.tr/Etkinlikler/Detay/tepebasi-belediyesi-mahalleler-arasi-nostaljik-futbol-turnuvasi',summary:'Belediyenin takviminde ilan edilen turnuva başlangıcı. Ayrıntılı maç programı ve kesin saha erişimi henüz rota verisine aktarılmadı.'},
 {...base,id:'tepebasi-genclik-2026-09-27',title:'Gençlik Tiyatrosu · Yeni dönem başvuruları',category:'workshop',district:'Tepebaşı',date:'2026-09-27',time:'17:00',venue:'Yer belirtilmedi',venueId:null,organizer:'Tepebaşı Belediyesi',sourceId:'tepebasi',sourceUrl:'https://www.tepebasi.bel.tr/Etkinlikler/Detay/tepebasi-belediyesi-genclik-tiyatrosu-yeni-donem-ogrencilerini-ariyor',summary:'Bu bir öğrenci alımı duyurusudur; seyirciye açık oyun seansı değildir.',status:'announced'},
 {...base,id:'tiyatro-verimsizler-2026',title:'Verimsizler · Yeni sezon duyurusu',category:'theatre',district:null,date:null,time:null,venue:'Seans ve sahne açıklanacak',venueId:null,organizer:'Eskişehir Büyükşehir Belediyesi Şehir Tiyatroları',sourceId:'tiyatro',sourceUrl:'https://tiyatro.eskisehir.bel.tr/haberdetay.php?haber=13359',summary:'Kurum yeni sezon oyununu duyurdu. Ekim için kesin seans tarihi ve sahne bilgisi yayımlanmadan rotaya eklenmez.',status:'announced',indoor:true},
];
