import type {EventSource} from './types';
export const eventSources:EventSource[]=[
 {id:'ebb',name:'Eskişehir Büyükşehir Belediyesi',url:'https://www.eskisehir.bel.tr/',district:null,kind:'municipality',adapter:'ebb-news'},
 {id:'tepebasi',name:'Tepebaşı Belediyesi',url:'https://www.tepebasi.bel.tr/Etkinlikler',district:'Tepebaşı',kind:'municipality',adapter:'tepebasi'},
 {id:'odunpazari',name:'Odunpazarı Belediyesi',url:'https://www.odunpazari.bel.tr/guncel/etkinlikler',district:'Odunpazarı',kind:'municipality',adapter:'structured'},
 {id:'valilik',name:'Eskişehir Valiliği',url:'https://www.eskisehir.gov.tr/',district:null,kind:'governorship',adapter:'structured'},
 {id:'ktb',name:'İl Kültür ve Turizm Müdürlüğü',url:'https://eskisehir.ktb.gov.tr/TR-447105/2026-haberler-ve-duyurular.html',district:null,kind:'directorate',adapter:'structured'},
 {id:'gsb',name:'Gençlik ve Spor İl Müdürlüğü',url:'https://eskisehir.gsb.gov.tr/',district:null,kind:'directorate',adapter:'structured'},
 {id:'tiyatro',name:'Büyükşehir Şehir Tiyatroları',url:'https://tiyatro.eskisehir.bel.tr/oyuntakvimi.php',district:null,kind:'culture',adapter:'structured'},
 {id:'senfoni',name:'Büyükşehir Senfoni Orkestrası',url:'https://senfoni.eskisehir.bel.tr/',district:null,kind:'culture',adapter:'structured'},
 {"id": "beylikova-gov", "name": "Beylikova Kaymakamlığı", "url": "https://www.beylikova.gov.tr/", "district": "Beylikova", "kind": "district", "adapter": "structured"},
 {"id": "inonu-gov", "name": "İnönü Kaymakamlığı", "url": "https://www.inonu.gov.tr/", "district": "İnönü", "kind": "district", "adapter": "structured"},
 {"id": "mahmudiye-gov", "name": "Mahmudiye Kaymakamlığı", "url": "https://www.mahmudiye.gov.tr/", "district": "Mahmudiye", "kind": "district", "adapter": "structured"},
 {"id": "saricakaya-gov", "name": "Sarıcakaya Kaymakamlığı", "url": "https://www.saricakaya.gov.tr/", "district": "Sarıcakaya", "kind": "district", "adapter": "structured"},
 {"id": "seyitgazi-gov", "name": "Seyitgazi Kaymakamlığı", "url": "https://www.seyitgazi.gov.tr/", "district": "Seyitgazi", "kind": "district", "adapter": "structured"},
 {"id": "sivrihisar-gov", "name": "Sivrihisar Kaymakamlığı", "url": "https://www.sivrihisar.gov.tr/", "district": "Sivrihisar", "kind": "district", "adapter": "structured"},
 {"id": "tepebasi-gov", "name": "Tepebaşı Kaymakamlığı", "url": "https://www.tepebasi.gov.tr/", "district": "Tepebaşı", "kind": "district", "adapter": "structured"},
 {"id": "alpu-bel", "name": "Alpu Belediyesi", "url": "https://www.alpu.bel.tr/", "district": "Alpu", "kind": "municipality", "adapter": "structured"},
 {"id": "gunyuzu-bel", "name": "Günyüzü Belediyesi", "url": "https://www.gunyuzu.bel.tr/", "district": "Günyüzü", "kind": "municipality", "adapter": "structured"},
 {"id": "mahmudiye-bel", "name": "Mahmudiye Belediyesi", "url": "https://www.mahmudiye.bel.tr/", "district": "Mahmudiye", "kind": "municipality", "adapter": "structured"},
 {"id": "mihalgazi-bel", "name": "Mihalgazi Belediyesi", "url": "https://mihalgazi.bel.tr/", "district": "Mihalgazi", "kind": "municipality", "adapter": "structured"},
 {"id": "mihaliccik-bel", "name": "Mihalıççık Belediyesi", "url": "https://www.mihaliccik.bel.tr/", "district": "Mihalıççık", "kind": "municipality", "adapter": "structured"},
 {"id": "saricakaya-bel", "name": "Sarıcakaya Belediyesi", "url": "https://www.saricakaya.bel.tr/", "district": "Sarıcakaya", "kind": "municipality", "adapter": "structured"},
 {"id": "seyitgazi-bel", "name": "Seyitgazi Belediyesi", "url": "https://www.seyitgazi.bel.tr/", "district": "Seyitgazi", "kind": "municipality", "adapter": "structured"},
 {"id": "alpu-gov", "name": "Alpu Kaymakamlığı", "url": "https://www.alpu.gov.tr/", "district": "Alpu", "kind": "district", "adapter": "structured"},
 {"id": "cifteler-gov", "name": "Çifteler Kaymakamlığı", "url": "https://www.cifteler.gov.tr/", "district": "Çifteler", "kind": "district", "adapter": "structured"},
 {"id": "gunyuzu-gov", "name": "Günyüzü Kaymakamlığı", "url": "https://www.gunyuzu.gov.tr/", "district": "Günyüzü", "kind": "district", "adapter": "structured"},
 {"id": "han-gov", "name": "Han Kaymakamlığı", "url": "https://www.han.gov.tr/", "district": "Han", "kind": "district", "adapter": "structured"},
 {"id": "mihalgazi-gov", "name": "Mihalgazi Kaymakamlığı", "url": "https://www.mihalgazi.gov.tr/", "district": "Mihalgazi", "kind": "district", "adapter": "structured"},
 {"id": "mihaliccik-gov", "name": "Mihalıççık Kaymakamlığı", "url": "https://www.mihaliccik.gov.tr/", "district": "Mihalıççık", "kind": "district", "adapter": "structured"},
 {"id": "odunpazari-gov", "name": "Odunpazarı Kaymakamlığı", "url": "https://www.odunpazari.gov.tr/", "district": "Odunpazarı", "kind": "district", "adapter": "structured"},
];
export const sourceById=Object.fromEntries(eventSources.map(s=>[s.id,s])) as Record<string,EventSource>;
export function safeSourceUrl(raw:string,source:EventSource){try{const u=new URL(raw,source.url),root=new URL(source.url);u.searchParams.sort();return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&u.hostname===root.hostname?u.href:null;}catch{return null;}}
