import { text as t, type Locale } from "../routing/types";
const labels = {
 skip:t("İçeriğe geç","Skip to content","Zum Inhalt","Aller au contenu","تخطَّ إلى المحتوى"),
 scan:t("QR keşif","QR discovery","QR entdecken","Découverte QR","اكتشاف QR"),
 title:t("Bir kod. Yeni bir hikâye.","One code. A new story.","Ein Code. Eine neue Geschichte.","Un code. Une nouvelle histoire.","رمز واحد. حكاية جديدة."),
 intro:t("Bir eser, bölge veya rota üzerindeki QR’ı okutun.","Scan a QR for a place, an object or a route.","QR eines Ortes, Objekts oder einer Route scannen.","Scannez le QR d’un lieu, d’une œuvre ou d’un parcours.","امسح رمز مكان أو أثر أو مسار."),
 camera:t("Kamerayla tara","Scan with camera","Mit Kamera scannen","Scanner avec la caméra","المسح بالكاميرا"),
 cameraHint:t("QR’ı çerçevenin içine alın. Kamera görüntüsü kaydedilmez veya gönderilmez.","Place the QR inside the frame. Camera images are not saved or uploaded.","QR im Rahmen platzieren. Kamerabilder werden weder gespeichert noch übertragen.","Placez le QR dans le cadre. Les images ne sont ni enregistrées ni envoyées.","ضع الرمز داخل الإطار. لا تُحفظ صور الكاميرا ولا تُرسل."),
 permission:t("Kamera açılamadı. Kamera iznini kontrol edin; fotoğraf seçebilir veya kısa kodu girebilirsiniz.","Camera unavailable. Check permission, choose a photo or enter the short code.","Kamera nicht verfügbar. Berechtigung prüfen, Foto wählen oder Kurzcode eingeben.","Caméra indisponible. Vérifiez l’autorisation, choisissez une photo ou saisissez le code.","تعذّر فتح الكاميرا. تحقّق من الإذن أو اختر صورة أو أدخل الرمز القصير."),
 photo:t("Fotoğraftan oku","Read a photo","Foto lesen","Lire une photo","قراءة صورة"),
 manual:t("Kodu elle gir","Enter a code","Code eingeben","Saisir le code","إدخال الرمز"),
 placeholder:t("Örn. E-0022 veya QR bağlantısı","E.g. E-0022 or QR link","Z. B. E-0022 oder QR-Link","Ex. E-0022 ou lien QR","مثال E-0022 أو رابط QR"),
 open:t("Rehberi aç","Open guide","Guide öffnen","Ouvrir le guide","فتح الدليل"),
 close:t("Kapat","Close","Schließen","Fermer","إغلاق"),
 loading:t("Hazırlanıyor…","Preparing…","Wird vorbereitet…","Préparation…","جارٍ التحضير…"),
 invalid:t("Bu kod Eskişehir rehber kataloğunda bulunamadı veya rota sürümü desteklenmiyor. Tabeladaki E- veya R- kodunu kontrol edin.","This code is not in the Eskişehir guide or its route version is unsupported. Check the E- or R- code on the sign.","Code nicht im Eskişehir-Guide oder Routenversion nicht unterstützt. E- oder R-Code auf dem Schild prüfen.","Code absent du guide ou version du parcours non prise en charge. Vérifiez le code E- ou R- sur le panneau.","الرمز غير موجود في دليل إسكي شهير أو إصدار المسار غير مدعوم. تحقّق من رمز E- أو R- على اللوحة."),
 noQr:t("Fotoğrafta okunabilir bir QR bulunamadı. Daha net bir fotoğraf deneyin.","No readable QR found. Try a clearer photo.","Kein lesbarer QR gefunden. Ein schärferes Foto versuchen.","Aucun QR lisible. Essayez une photo plus nette.","لم يُعثر على رمز مقروء. جرّب صورة أوضح."),
 torch:t("Fener","Torch","Licht","Lampe","المصباح"),
 recent:t("Son açılanlar","Recently opened","Zuletzt geöffnet","Ouverts récemment","فُتحت مؤخرًا"),
 clear:t("Geçmişi temizle","Clear history","Verlauf löschen","Effacer l’historique","مسح السجل"),
 browse:t("Rehberleri keşfet","Browse guides","Guides entdecken","Parcourir les guides","استعراض الأدلة"),
 places:t("Eserler & bölgeler","Places & objects","Orte & Objekte","Lieux & œuvres","الأماكن والآثار"),
 themes:t("Tematik rotalar","Themed routes","Themenrouten","Parcours thématiques","مسارات موضوعية"),
 search:t("Ad, ilçe veya kısa kod ara","Search name, district or code","Name, Bezirk oder Code suchen","Rechercher un nom, district ou code","ابحث بالاسم أو المقاطعة أو الرمز"),
 all:t("Tüm ilçeler","All districts","Alle Bezirke","Tous les districts","كل المقاطعات"),
 more:t("Daha fazla göster","Show more","Mehr anzeigen","Afficher plus","عرض المزيد"),
 empty:t("Bu aramada rehber bulunamadı.","No guides match this search.","Keine passenden Guides gefunden.","Aucun guide ne correspond.","لا توجد أدلة مطابقة للبحث."),
 story:t("Hikâyesi","The story","Die Geschichte","Son histoire","الحكاية"),
 detail:t("Yakından bak","Take a closer look","Genauer hinsehen","Regarder de plus près","نظرة أقرب"),
 practical:t("Ziyaret notları","Visit notes","Besuchshinweise","Conseils de visite","ملاحظات الزيارة"),
 sources:t("Kaynaklar","Sources","Quellen","Sources","المصادر"),
 sourceHint:t("İçerik kaynağını ve güncel ziyaret koşullarını inceleyin.","Check the content source and current visiting conditions.","Quelle und aktuelle Besuchsbedingungen prüfen.","Consultez la source et les conditions de visite actuelles.","راجع مصدر المعلومات وشروط الزيارة الحالية."),
 listen:t("Metni dinle","Listen to the text","Text anhören","Écouter le texte","الاستماع للنص"),
 stop:t("Durdur","Stop","Stoppen","Arrêter","إيقاف"),
 audioHint:t("Cihazınızın sesli okuma özelliği kullanılır; stüdyo kaydı değildir.","Uses your device’s text-to-speech; not a recorded audio guide.","Nutzt die Vorlesefunktion des Geräts; keine Studioaufnahme.","Utilise la lecture vocale de l’appareil ; ce n’est pas un enregistrement.","يستخدم قراءة النص في جهازك؛ وليس تسجيلًا صوتيًا."),
 noVoice:t("Bu dilde kullanılabilir ses bulunamadı. Cihazınıza ilgili dil sesini ekleyebilirsiniz.","No voice for this language is available. You can install one on your device.","Keine Stimme in dieser Sprache verfügbar. Sie können eine auf dem Gerät installieren.","Aucune voix disponible dans cette langue. Vous pouvez l’installer sur votre appareil.","لا يتوفر صوت بهذه اللغة. يمكنك تثبيته على جهازك."),
 plan:t("Bu durakla rota oluştur","Plan with this stop","Mit diesem Stopp planen","Planifier avec cette étape","التخطيط بهذه المحطة"),
 planTheme:t("Rotayı kişiselleştir","Personalise this route","Route anpassen","Personnaliser le parcours","تخصيص المسار"),
 navigate:t("Yol tarifi","Directions","Wegbeschreibung","Itinéraire","الاتجاهات"),
 qrShare:t("QR ile paylaş","Share with QR","Per QR teilen","Partager par QR","المشاركة برمز QR"),
 share:t("Bağlantıyı paylaş","Share link","Link teilen","Partager le lien","مشاركة الرابط"),
 copied:t("Bağlantı kopyalandı.","Link copied.","Link kopiert.","Lien copié.","نُسخ الرابط."),
 copyFailed:t("Bağlantıyı aşağıdaki alandan kopyalayabilirsiniz.","Copy the link from the field below.","Link aus dem Feld unten kopieren.","Copiez le lien dans le champ ci-dessous.","انسخ الرابط من الحقل أدناه."),
 print:t("QR kartını yazdır / PDF","Print QR card / PDF","QR-Karte drucken / PDF","Imprimer la carte QR / PDF","طباعة بطاقة QR / PDF"),
 appOpen:t("Uygulamada aç","Open in app","In App öffnen","Ouvrir dans l’app","الفتح في التطبيق"),
 appHint:t("Eskişehir Cebimde bu telefonda kuruluysa açılır. Rehbere buradan da devam edebilirsiniz.","Opens if Eskişehir Cebimde is installed. You can also continue here.","Öffnet die installierte App Eskişehir Cebimde. Sie können auch hier fortfahren.","Ouvre Eskişehir Cebimde si elle est installée. Vous pouvez aussi continuer ici.","يفتح إسكي شهير جيبيمده إن كان مثبتًا. يمكنك المتابعة هنا أيضًا."),
 preview:t("Paylaşılan gezi","Shared trip","Geteilte Reise","Voyage partagé","رحلة مشتركة"),
 importHint:t("Tarih, ulaşım ve durakları kontrol edip planı açın. Geziniz otomatik olarak başlatılmaz.","Review the date, transport and stops before opening. Your trip does not start automatically.","Datum, Verkehrsmittel und Stopps prüfen. Die Reise startet nicht automatisch.","Vérifiez la date, le transport et les étapes. Le voyage ne démarre pas automatiquement.","راجع التاريخ ووسيلة النقل والمحطات قبل الفتح. لا تبدأ الرحلة تلقائيًا."),
 openPlan:t("Gezi planını aç","Open trip plan","Reiseplan öffnen","Ouvrir le programme","فتح خطة الرحلة"),
 unavailable:t("Paylaşılan plan bu katalogla yeniden oluşturulamadı. Tercihleri açıp yeni alternatifler oluşturabilirsiniz.","This plan could not be reproduced with this catalogue. Open its preferences to create new alternatives.","Plan mit diesem Katalog nicht reproduzierbar. Einstellungen öffnen, um neue Alternativen zu erstellen.","Ce programme ne peut pas être reproduit. Ouvrez ses préférences pour créer des alternatives.","تعذّرت إعادة إنشاء الخطة بهذا الكتالوج. افتح التفضيلات لإنشاء بدائل جديدة."),
 localOnly:t("Tarama geçmişi yalnızca bu cihazda saklanır.","Scan history stays on this device.","Scanverlauf bleibt auf diesem Gerät.","L’historique reste sur cet appareil.","يبقى سجل المسح على هذا الجهاز."),
 guideNote:t("Dijital rehber kodları hazır. Sahadaki tabela yerleşimi ayrı bir uygulama aşamasıdır.","Digital guide codes are ready. Physical signage is a separate rollout stage.","Digitale Codes sind bereit. Beschilderung vor Ort folgt als eigener Schritt.","Les codes sont prêts. La signalétique sur place relève d’une étape distincte.","رموز الدليل جاهزة. تركيب اللوحات الميدانية مرحلة منفصلة."),
 stops:t("durak","stops","Stopps","étapes","محطات"),
 homeTitle:t("Bugün ne keşfedelim?","What will you discover?","Was entdecken wir heute?","Que découvrir aujourd’hui ?","ماذا نكتشف اليوم؟"),
 routeAction:t("Rotanı oluştur","Plan your route","Route planen","Créer un parcours","خطّط لمسارك"),
 routeHint:t("Zamanına ve ilgi alanlarına göre","For your time and interests","Nach Zeit und Interessen","Selon votre temps et vos envies","حسب وقتك واهتماماتك"),
 scanHint:t("Önündeki eserin hikâyesini aç","Discover the story in front of you","Die Geschichte vor dir entdecken","L’histoire juste devant vous","اكتشف حكاية ما أمامك"),
 themesTitle:t("Bir tema seç, yola çık.","Choose a theme. Explore.","Thema wählen. Entdecken.","Un thème. Une découverte.","اختر موضوعًا وانطلق."),
 heritage:t("Lezzet & miras","Taste & heritage","Genuss & Kulturerbe","Saveurs & patrimoine","المذاق والتراث"),
 heritageHint:t("Tescilli lezzetler, yerel ustalık","Local flavours and craftsmanship","Regionale Küche und Handwerk","Saveurs locales et savoir-faire","المذاقات والحرف المحلية"),
 continue:t("Gezine devam et","Continue your trip","Reise fortsetzen","Continuer le voyage","متابعة رحلتك"),
 institution:t("Birliği tanı","Meet the institution","Die Institution","L’institution","تعرّف إلى الاتحاد"),
 institutionHint:t("Şehrin turizmine ortak bir gelecek","A shared future for city tourism","Gemeinsame Zukunft für den Tourismus","Un avenir commun pour le tourisme","مستقبل مشترك لسياحة المدينة"),
 language:t("Dil","Language","Sprache","Langue","اللغة"),
 back:t("Geri","Back","Zurück","Retour","رجوع"),
 code:t("Rehber kodu","Guide code","Guide-Code","Code du guide","رمز الدليل"),
 home:t("Keşfet","Discover","Entdecken","Découvrir","اكتشف"),
 route:t("Rota","Route","Route","Parcours","المسار"),
 trips:t("Gezilerim","My trips","Reisen","Mes voyages","رحلاتي"),
 union:t("Birlik","Institution","Institution","Institution","الاتحاد"),
};
export const qrCopy=(locale:Locale)=>Object.fromEntries(Object.entries(labels).map(([key,value])=>[key,value[locale]])) as Record<keyof typeof labels,string>;
