/** Visual interpretations of the award forms described in the project documents. */
export const awardDesigns = [
  {
    id: 'altin-midas',
    name: 'Altın Midas',
    image: 'altin-midas',
    symbol: 'Anlatım gücü ve özgün bakış',
    meaning: 'Genç sinemacıların anlatım gücünü ve özgün bakışını görünür kılar. Midas adını taşıyan ödül, Frigya’nın kültürel belleği ile bugünün sinemasını aynı nesnede buluşturur.',
    form: 'Midas Anıtı’nın üçgen alınlığı ve geometrik cephesinden esinlenen oyma lületaşı formu.',
    note: 'Kısa Kurmaca ve Kısa Belgesel için iki ayrı Altın Midas verilmesi planlanır.',
    alt: 'Altın Midas tasarım önerisi: Midas Anıtı cephesini yorumlayan, ince altın renkli vurgulara sahip beyaz lületaşı ödül.',
  },
  {
    id: 'gumus-midas',
    name: 'Gümüş Midas',
    image: 'gumus-midas',
    symbol: 'İlk filmler, gelişen bir sinema dili',
    meaning: 'Öğrencilik döneminde filizlenen sinema dilini ve üretim cesaretini destekler. Eğitimden bağımsız üretime uzanan yolculuğun ilk adımlarını simgeler.',
    form: 'Midas ailesinin cephe geometrisini koruyan, gümüş renkli ayrıntılarla yorumlanmış lületaşı tasarım önerisi.',
    note: '',
    alt: 'Gümüş Midas tasarım önerisi: geometrik cephe kabartmaları ve gümüş renkli ayrıntıları olan beyaz lületaşı ödül.',
  },
  {
    id: 'frigya-ozel',
    name: 'Frigya Özel Ödülü',
    image: 'frigya-ozel',
    symbol: 'Mekân, hafıza ve üretim',
    meaning: 'Eskişehir’i film üretiminin mekânı olarak öne çıkarır. Kentin ve ilçelerin kültürel hafızasını yeni filmlere taşıma fikrini temsil eder; şehirde çekilen yapımları teşvik eder.',
    form: 'Frigya’nın kaya anıtlarını hatırlatan, merkezindeki açıklığı geometrik kabartmalarla çevreleyen lületaşı cephe.',
    note: 'Ana seçkideki bir film bu ödüle de aday olabilir; ikinci kez gösterilmez.',
    alt: 'Frigya Özel Ödülü tasarım önerisi: ortasında açıklık bulunan, Frig cephe desenlerinden esinlenmiş beyaz lületaşı heykel.',
  },
  {
    id: 'porsuk',
    name: 'Porsuk Ödülü',
    image: 'porsuk',
    symbol: 'Seyirciyle kurulan bağ',
    meaning: 'Seyircinin filmle kurduğu bağı ve ortak sinema deneyimini temsil eder. Nehrin akışından türetilen form, hikâyelerin insanlar ve şehir arasında dolaşmasını simgeler.',
    form: 'Porsuk’un kıvrımlarını dikey bir akışa dönüştüren, lületaşından nehir formu.',
    note: 'Uzun Metraj bölümünün ödülü seyirci oyuyla belirlenir.',
    alt: 'Porsuk Ödülü tasarım önerisi: nehrin akışını çağrıştıran S kıvrımlı beyaz lületaşı heykel.',
  },
  {
    id: 'ham-luletasi',
    name: 'Ham Lületaşı',
    image: 'ham-luletasi',
    symbol: 'Gençliğin yaratıcı potansiyeli',
    meaning: 'Henüz biçimini tamamlamamış yaratıcı potansiyeli anlatır. Taşın işlenmemiş hali, genç bir sinemacının kendi dilini bulma ve dönüşme ihtimalini görünür kılar. Ödülün gençler tarafından verilmesi bu bakışı tamamlar.',
    form: 'Doğal dokusu ve düzensiz yüzeyi korunan, işlenmemiş lületaşı bloğu.',
    note: 'Gençlik Jürisi Seçkisi’ndeki 15 film, 16–22 yaş aralığındaki yedi jüri üyesi tarafından değerlendirilir.',
    alt: 'Ham Lületaşı ödülü tasarım önerisi: doğal, gözenekli dokusu korunmuş düzensiz beyaz ham taş bloğu.',
  },
] as const;
