import {freshApplication,requiredSlots,slotLabels,type Application,type State,type EventItem} from './domain.ts';
export const demoFiles=(a:Application)=>requiredSlots(a).map(slot=>({slot,name:`demo-${slot}.txt`,type:'text/plain',size:48,data:'data:text/plain;base64,REVNTyBCRUxHRVNJLiBHZXJjZWsgYmVsZ2UgZGVnaWxkaXIu'}));
export function sampleApplication():Application{const a=freshApplication();Object.assign(a,{name:'Deniz Örnek',email:'deniz@example.test',phone:'',title:'Son Sefer — Demo',directors:[{name:'Deniz Örnek',dob:'2002-04-15',citizen:true}],duration:14,completed:'2026-06-10',city:'Eskişehir',short:'Son tramvayı bekleyen iki yabancı, aynı şehrin farklı hikâyelerini paylaşır.',synopsis:'Genç bir sinemacı, gece vardiyasından dönen bir yolcuyla son durakta karşılaşır. Bekleyiş boyunca birbirlerini dinlemeleri, şehre ve kendi hayatlarına yeni bir gözle bakmalarını sağlar. Bu anlatı yalnızca demo başvurusunu denemek için oluşturulmuştur.',bio:'Deniz Örnek, demo deneyimi için oluşturulmuş temsili bir yönetmendir. Kısa film ve kent hikâyeleri üzerine çalışan kurgusal bir profildir.',note:'Kent hayatındaki küçük karşılaşmaları sade bir anlatımla görünür kılmayı amaçlayan temsili bir film projesidir.',watchUrl:'https://example.com/demo-film',rights:true,consent:true});a.files=demoFiles(a);return a;}
export const seedEvents:EventItem[]=[
 ['e1',24,'14:00','Akreditasyon ve karşılama','Buluşma','Festival merkezi · yer duyurulacak',120,160],['e2',24,'19:30','Açılış galası ve açılış filmi','Gala','Ana salon · yer duyurulacak',120,300],
 ['e3',25,'11:00','Kısa Kurmaca · Gösterim bloğu 1','Gösterim','Ana salon · yer duyurulacak',90,180],['e4',25,'14:00','Bir sahnenin anatomisi','Atölye','Atölye alanı · yer duyurulacak',90,25],['e5',25,'16:30','Kısa Belgesel · Gösterim bloğu 1','Gösterim','Ana salon · yer duyurulacak',100,180],['e6',25,'21:00','Yıldızların altında uzun metraj','Açık hava','Açık hava alanı · yer duyurulacak',110,250],
 ['e7',26,'11:00','Öğrenci Filmleri · Gösterim bloğu','Gösterim','Ana salon · yer duyurulacak',90,180],['e8',26,'14:00','Hikâyeyi kurgu masasında bulmak','Atölye','Atölye alanı · yer duyurulacak',90,25],['e9',26,'17:00','Genç yönetmenlerle söyleşi','Söyleşi','Festival merkezi · yer duyurulacak',60,100],['e10',26,'21:00','Açık hava · Seyirci seçimi','Açık hava','Açık hava alanı · yer duyurulacak',120,250],
 ['e11',27,'11:00','Gençlik Jürisi Seçkisi','Gösterim','Ana salon · yer duyurulacak',100,180],['e12',27,'14:00','Mekânın hafızası: Frigya','Söyleşi','Festival merkezi · yer duyurulacak',60,100],['e13',27,'19:30','Midas Ödülleri · Kapanış töreni','Tören','Ana salon · yer duyurulacak',120,300]
].map(([id,day,time,title,type,place,duration,capacity])=>({id:String(id),day:Number(day),time:String(time),title:String(title),type:String(type),place:String(place),duration:Number(duration),capacity:Number(capacity),demo:true}));
export function initialState():State{
 const names=['Son Sefer','Taşın Hafızası','Sarı Pencere','Başka Bir Sabah','Yolun Sesi','Kıyıda','İlk Kadraj','Sessiz Avlu'];
 const cats=['fiction','documentary','student','feature','documentary','fiction','student','fiction'];
 const statuses=['received','correction','review','eligible','evaluated','selected','received','third'];
 const applications=names.map((title,i)=>{const a=sampleApplication();a.id=`demo-${i+1}`;a.code=`EGFF-DEMO-${1001+i}`;a.title=`${title} — Demo`;a.name=`${['Deniz','Ekin','Ada','Arda','Duru','Can','Ece','Mert'][i]} Örnek`;a.email=`demo${i+1}@example.test`;a.directors[0].name=a.name;a.category=cats[i];a.duration=i===3?82:12+i;a.school=i===2||i===6?'Demo Sinema Okulu':'';a.status=statuses[i] as Application['status'];a.localFilm=i===1||i===4||i===5;a.locations=a.localFilm?'Han / Yazılıkaya':'';a.createdAt=`2027-03-${String(10+i).padStart(2,'0')}T10:00:00Z`;a.updatedAt=a.createdAt;a.history=[{at:a.createdAt,text:'Demo başvurusu oluşturuldu.',actor:'Başvuru sahibi'}];a.files=demoFiles(a);if(i===1){a.dueAt='2027-04-12T14:00:00Z';a.history.push({at:'2027-04-05T14:00:00Z',text:'Film afişi daha yüksek çözünürlükte yeniden eklenmeli. Beş iş günü içinde güncelleyin.',actor:'Sekretarya (demo)'});}if([2,4,5,7].includes(i)){a.assigned=['juri-1','juri-2'];if([4,5,7].includes(i)){const one=[17,12,12,8,9,8,4,8,4];const two=i===7?[10,7,6,4,4,5,2,5,2]:[18,13,13,8,8,9,4,9,4];a.reviews=[{reviewer:'juri-1',scores:one,note:'Temsili bağımsız değerlendirme.',conflict:false,at:'2027-04-20T12:00:00Z'},{reviewer:'juri-2',scores:two,note:'Temsili bağımsız değerlendirme.',conflict:false,at:'2027-04-21T12:00:00Z'}];if(i===7)a.assigned.push('juri-3');}}return a;});
 return {version:1,applications,events:seedEvents,reservations:[],selections:{youth:[],local:[]},updatedAt:new Date().toISOString()};
}
