import {freshApplication,validateApplication,type Application,type State,type EventItem,type Reservation} from './domain.ts';
import {applyAction,redactApplicant,redactReviewer,type Actor,type ActionPayload} from './actions.ts';
import {initialState} from './seed.ts';
declare global{interface Window{EGFF_CONFIG?:{mode:'demo'|'live';apiBase:string;privacyUrl?:string;rulesUrl?:string};}}
export const config=():NonNullable<Window['EGFF_CONFIG']>=>typeof window==='undefined'?{mode:'demo',apiBase:''}:window.EGFF_CONFIG||{mode:'demo',apiBase:''};
export const isDemo=()=>config().mode!=='live';
let dbPromise:Promise<IDBDatabase>|undefined;
function db(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{if(!window.indexedDB){reject(Error('Tarayıcı kalıcı depolamayı desteklemiyor. Normal bir tarayıcı penceresinde açın.'));return;}const req=indexedDB.open('egff-demo-2027',1);req.onupgradeneeded=()=>req.result.createObjectStore('data');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(Error('Demo kayıt alanı açılamadı. Tarayıcı depolama izinlerini kontrol edin.'));req.onblocked=()=>reject(Error('Eski demo sekmelerini kapatıp yeniden deneyin.'));});return dbPromise;}
async function transaction<T>(fn:(s:State)=>T):Promise<T>{const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('data','readwrite');const st=tx.objectStore('data');const req=st.get('state');let result:T;req.onsuccess=()=>{try{const state=(req.result as State)||initialState();result=fn(state);st.put(state,'state');}catch(e){tx.abort();reject(e);}};tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(Error('Kayıt saklanamadı. Depolama alanını kontrol edin.'));});}
let staffToken='';let currentActor:Actor|null=null;
export const getActor=()=>currentActor;
async function request<T>(path:string,data?:unknown,method='POST'):Promise<T>{const base=config().apiBase?.replace(/\/$/,'');if(!base)throw Error('Başvuru hizmeti henüz bağlanmamış. Lütfen daha sonra tekrar deneyin.');let res:Response;try{res=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(staffToken?{Authorization:'Bearer '+staffToken}:{})},...(method==='GET'?{}:{body:JSON.stringify(data||{})}),signal:AbortSignal.timeout(20000)});}catch{throw Error('Hizmete ulaşılamıyor. Kaydınızın gönderildiğini varsaymayın; yeniden deneyin.');}const body=await res.json() as {error?:string};if(!res.ok)throw Error(body.error||'İşlem tamamlanamadı.');return body as T;}
export const loadPublic=async()=>isDemo()?transaction(s=>({events:s.events.filter(e=>e.published!==false),films:s.applications.filter(a=>a.status==='selected').map(a=>({id:a.id,title:a.title,category:a.category,duration:a.duration,short:a.short})),selections:s.selections})):request<{events:EventItem[];films:Partial<Application>[];selections:State['selections']}>('/public',undefined,'GET');
export async function submitApplication(input:Application){if(!isDemo())return request<Application>('/applications',input);const errors=validateApplication(input);if(errors.length)throw Error(errors.join(' '));return transaction(s=>{if(input.kind==='film'&&s.applications.some(a=>a.kind==='film'&&a.title.trim().toLocaleLowerCase('tr')===input.title.trim().toLocaleLowerCase('tr')&&a.directors[0]?.name.trim().toLocaleLowerCase('tr')===input.directors[0]?.name.trim().toLocaleLowerCase('tr')))throw Error('Bu film için bir başvuru zaten var. Takip ekranını kullanın.');const now=new Date().toISOString();const a:Application={...freshApplication(input.kind),...input,id:crypto.randomUUID(),code:'EGFF-'+crypto.randomUUID().replace(/-/g,'').toUpperCase(),createdAt:now,updatedAt:now,status:'received',assigned:[],reviews:[],history:[{at:now,text:'Başvuru alındı. Uygunluk kontrolü bekleniyor.',actor:'Başvuru sahibi'}],demo:true};s.applications.push(a);return redactApplicant(a);});}
export async function track(email:string,code:string){if(!isDemo())return request<Application>('/track',{email,code});return transaction(s=>{const a=s.applications.find(a=>a.email.toLowerCase()===email.trim().toLowerCase()&&a.code===code.trim());if(!a)throw Error('E-posta ve takip koduyla eşleşen başvuru bulunamadı.');return redactApplicant(a);});}
export async function correct(id:string,code:string,patch:Partial<Application>){if(!isDemo())return request<Application>('/correction',{id,code,patch});return transaction(s=>{const a=s.applications.find(x=>x.id===id&&x.code===code);if(!a||a.status!=='correction')throw Error('Bu başvuru güncellemeye açık değil.');if(a.dueAt&&new Date(a.dueAt)<new Date()&&!a.demo)throw Error('Düzeltme süresi dolmuş.');for(const key of ['short','synopsis','bio','note','watchUrl','watchPassword','files'] as const){if(patch[key]!==undefined)(a as unknown as Record<string,unknown>)[key]=patch[key];}const errors=validateApplication(a);if(errors.length)throw Error(errors.join(' '));a.status='received';a.dueAt=undefined;a.updatedAt=new Date().toISOString();a.history.push({at:a.updatedAt,text:'İstenen düzeltmeler gönderildi; yeniden kontrol bekleniyor.',actor:'Başvuru sahibi'});return redactApplicant(a);});}
export async function login(username:string,password:string){if(isDemo()){currentActor={id:username==='admin'?'admin':username,role:username==='admin'?'admin':'reviewer'};return currentActor;}const result=await request<{token:string;actor:Actor}>('/staff/login',{username,password});staffToken=result.token;currentActor=result.actor;return currentActor;}
export function logout(){if(!isDemo()&&staffToken)void request('/staff/logout').catch(()=>{});staffToken='';currentActor=null;}
export async function staffState():Promise<State>{if(!currentActor)throw Error('Lütfen oturum açın.');if(!isDemo())return request<State>('/staff/state',undefined,'GET');return transaction(s=>currentActor!.role==='admin'?s:{...s,reservations:[],applications:s.applications.filter(a=>a.assigned.includes(currentActor!.id)).map(a=>redactReviewer(a,currentActor!.id))});}
export async function action(name:string,p:ActionPayload){if(!currentActor)throw Error('Lütfen oturum açın.');if(!isDemo())return request('/staff/action',{action:name,payload:p});return transaction(s=>{applyAction(s,name,p,currentActor!);return {ok:true};});}
export async function reserve(eventId:string,name:string,email:string,count:number):Promise<Reservation>{if(!isDemo())throw Error('Bilet satışı resmî satış altyapısı açıldığında başlayacaktır.');return transaction(s=>{const event=s.events.find(e=>e.id===eventId);if(!event||!Number.isInteger(count)||count<1||count>4||!name.trim()||! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Rezervasyon bilgilerini kontrol edin.');const used=s.reservations.filter(r=>r.eventId===eventId).reduce((n,r)=>n+r.count,0);if(used+count>event.capacity)throw Error('Bu etkinlikte yeterli kontenjan kalmadı.');const r={id:'DEMO-'+crypto.randomUUID().slice(0,8).toUpperCase(),name,email,count,eventId,createdAt:new Date().toISOString(),demo:true};s.reservations.push(r);return r;});}
export async function saveDraft(a:Application){if(isDemo()){const d=await db();return new Promise<void>((resolve,reject)=>{const tx=d.transaction('data','readwrite');tx.objectStore('data').put(a,'draft');tx.oncomplete=()=>resolve();tx.onerror=()=>reject(Error('Taslak kaydedilemedi.'));});}throw Error('Canlı başvuruyu tamamlayıp gönderin.');}
export async function getDraft(){if(!isDemo())return null;const d=await db();return new Promise<Application|null>((resolve,reject)=>{const req=d.transaction('data').objectStore('data').get('draft');req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(Error('Taslak okunamadı.'));});}
export async function clearDraft(){if(isDemo()){const d=await db();d.transaction('data','readwrite').objectStore('data').delete('draft');}}
export function download(name:string,content:string,mime='text/plain;charset=utf-8'){const blob=new Blob([content],{type:mime});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
export function exportCSV(apps:Application[]){const esc=(s:unknown)=>'"'+String(s??'').replace(/^(\s*[=+@-]|[\t\r\n])/,"'$&").replace(/"/g,'""')+'"';const rows=[['Başvuru','Tür','Film / Program','Ad Soyad','E-posta','Bölüm','Durum','Tarih'],...apps.map(a=>[a.id,a.kind,a.title||a.choice,a.name,a.email,a.category,a.status,a.createdAt])];download('EGFF-basvurular.csv','\ufeff'+rows.map(r=>r.map(esc).join(';')).join('\r\n'),'text/csv;charset=utf-8');}

export async function staffDetail(id:string):Promise<Application>{if(!currentActor)throw Error('Oturum açın.');if(!isDemo())return request<Application>('/staff/detail',{id});return transaction(s=>{const a=s.applications.find(x=>x.id===id);if(!a)throw Error('Başvuru bulunamadı.');if(currentActor!.role==='reviewer'){if(!a.assigned.includes(currentActor!.id))throw Error('Erişim yok.');return redactReviewer(a,currentActor!.id);}return a;});}
