/** Editorial proposals only. No entry represents a confirmed commercial relationship. */
export type SponsorCompany = {
  id: string;
  name: string;
  connection: string;
  fact: string;
  rationale: string;
  source: string;
  sourceLabel: string;
  demo: true;
};

export const sponsorCompanies: SponsorCompany[] = [
  {id:'eti',name:'ETİ',connection:'Eskişehir kökenli · Gıda',fact:'İlk bisküvi üretim tesisi 1962’de Eskişehir’de faaliyete başladı.',rationale:'Şehirle bağı ve ulusal marka yapısı nedeniyle festivalin bütününe destek için örnek olarak önerildi.',source:'https://www.etietieti.com/company/facilities',sourceLabel:'ETİ · Üretim tesisleri',demo:true},
  {id:'isbank',name:'Türkiye İş Bankası',connection:'Ulusal · Kültür ve sanat',fact:'İş Sanat bünyesinde sahne sanatları, müzeler ve atölyeler yer alıyor.',rationale:'Kültür ve öğrenme alanlarıyla ilişkisi nedeniyle yıl boyu ücretsiz Akademi programına örnek olarak önerildi.',source:'https://issanat.com.tr/',sourceLabel:'İş Sanat · Program ve atölyeler',demo:true},
  {id:'ford',name:'Ford Otosan',connection:'Eskişehir’de üretim · Otomotiv',fact:'İnönü’de Eskişehir Fabrikası bulunuyor.',rationale:'Yerel üretim bağı ve ulaşım sektörüyle ilişkisi nedeniyle Frigya Rotası, gezici gösterimler ve transfer desteğine örnek olarak önerildi.',source:'https://kap.org.tr/en/sirket-bilgileri/genel/956-ford-otomotiv-sanayi-a-s',sourceLabel:'KAP · Ford Otosan şirket bilgileri',demo:true},
  {id:'sarar',name:'SARAR',connection:'Eskişehir kökenli · Tekstil',fact:'1944’te Eskişehir’de kuruldu; şirket kültür, sanat ve eğitim alanlarındaki desteklerini açıklıyor.',rationale:'Şehirle bağı nedeniyle ödül üretimi ve tören giderlerine destek; tekstil alanı nedeniyle tören ekibinin kıyafet ihtiyacı için örnek olarak önerildi.',source:'https://sarar.com/hakkimizda',sourceLabel:'SARAR · Hakkımızda',demo:true},
  {id:'canon',name:'Canon Türkiye',connection:'Türkiye’de faaliyet · Görüntüleme',fact:'Profesyonel video ve Cinema EOS kamera ürünleri sunuyor.',rationale:'Genç sinemacıların kamera ve çekim atölyeleri için ekipman ödüncü ve uzmanlık desteğine örnek olarak önerildi.',source:'https://www.canon.com.tr/',sourceLabel:'Canon Türkiye · Video kamera ürünleri',demo:true},
  {id:'turkcell',name:'Turkcell',connection:'Ulusal · İletişim ve teknoloji',fact:'Kurumsal iletişim, bulut ve dijital iş hizmetleri sunuyor.',rationale:'Festival bağlantısı, dijital yayın altyapısı ve erişilebilir içerik giderlerine destek için örnek olarak önerildi.',source:'https://www.turkcell.com.tr/kurumsal',sourceLabel:'Turkcell · Kurumsal çözümler',demo:true},
  {id:'tasigo',name:'Tasigo Eskişehir',connection:'Eskişehir’de işletme · Konaklama',fact:'Eskişehir’de konaklama, toplantı ve etkinlik alanları sunuyor.',rationale:'Konuk sinemacı, eğitmen ve jüri üyelerinin konaklama ihtiyacına örnek olarak önerildi.',source:'https://www.tasigoeskisehir.com/en',sourceLabel:'Tasigo Eskişehir · Otel ve etkinlikler',demo:true},
  {id:'espark',name:'Espark',connection:'Eskişehir’de mekân · Alışveriş merkezi',fact:'Eskişehir’de yer alıyor ve ECE Türkiye tarafından yönetiliyor.',rationale:'Şehir içi tanıtım, buluşma ve izinleri netleştirilecek etkinlik alanı desteğine örnek olarak önerildi.',source:'https://www.espark.com.tr/avm/hakkimizda/',sourceLabel:'Espark · Hakkımızda',demo:true},
  {id:'kahve',name:'Kahve Dünyası',connection:'Ulusal · Kahve ve ikram',fact:'Kahve, çikolata ve unlu mamul ürünleri sunuyor.',rationale:'Gönüllü ekibi ve atölye katılımcıları için ikram ve mola alanı desteğine örnek olarak önerildi.',source:'https://www.kahvedunyasi.com/uretim',sourceLabel:'Kahve Dünyası · Üretim',demo:true},
  {id:'eskisehirnet',name:'Eskişehir.net',connection:'Yerel · Haber yayıncılığı',fact:'Eskişehir haberleri ve yerel gelişmeler yayımlıyor.',rationale:'Şehirde başvuru ve program duyurularını görünür kılacak yerel medya desteğine örnek olarak önerildi.',source:'https://www.eskisehir.net/eskisehir-son-dakika',sourceLabel:'Eskişehir.net · Yerel haberler',demo:true},
  {id:'beyazperde',name:'Beyazperde',connection:'Ulusal · Sinema yayıncılığı',fact:'Sinema haberleri, film eleştirileri ve röportajlar yayımlıyor.',rationale:'Türkiye’deki sinemaseverlere ve genç sinemacılara ulaşacak duyuru alanları için örnek olarak önerildi.',source:'https://www.beyazperde.com/',sourceLabel:'Beyazperde · Sinema yayınları',demo:true},
];

export const sponsorGroups = [
  {id:'main',number:'01',name:'Ana sponsor',scope:'Festivalin genel bütçesi ve ortak ihtiyaçları',visibility:'Festival genelinde öncelikli marka alanı; açılış ve kapanışta teşekkür',capacity:'1 ana sponsor önerisi'},
  {id:'program',number:'02',name:'Program sponsorları',scope:'Akademi, Frigya Rotası, gezici sinema ve ödüller',visibility:'Desteklenen programın sayfası, duyuruları ve etkinlik alanında görünürlük',capacity:'Her program için ayrı paket'},
  {id:'service',number:'03',name:'Hizmet ve mekân partnerleri',scope:'Ekipman, bağlantı, konaklama, mekân ve ikram',visibility:'İlgili hizmet noktasında tanıtım ve partner listesinde yer alma',capacity:'İhtiyaç ve kapasiteye göre'},
  {id:'media',number:'04',name:'Medya partnerleri',scope:'Yerel ve ulusal program duyuruları; tanıtım alanları',visibility:'Medya partnerleri alanında yer alma ve basın etkinliklerine erişim',capacity:'Yerel ve ulusal ayrı kapsam'},
] as const;

export type SponsorArea = {
  id:string; group:typeof sponsorGroups[number]['id']; title:string; summary:string;
  companies:string[]; contribution:string[]; period:string; covers:string[]; benefits:string[]; measure:string; note?:string;
};

export const sponsorAreas: SponsorArea[] = [
  {id:'ana-sponsor',group:'main',title:'Ana sponsor',summary:'Festivalin gerçekleşmesini sağlayan ortak bütçeye en geniş katkı.',companies:['eti'],contribution:['Nakdi'],period:'2027 edisyonunun duyuru, festival ve sonuç iletişimi',covers:['Gösterim organizasyonu, teknik kurulum ve genel yapım giderleri.','Genç sinemacıların katılımını ve ücretsiz programları destekleyen ortak bütçe.'],benefits:['Web sitesi ve festivalin ortak tanıtım malzemelerinde en üst sponsor düzeyi.','Açılış ve kapanış teşekkürleri; kapsamı birlikte belirlenecek marka deneyim alanı.','Mutabık kalınan davetli kontenjanı ve edisyon sonunda toplu faaliyet raporu.'],measure:'Gerçekleşen etkinlikler, toplam katılım ve belgelenen marka görünürlüğü.',note:'Tek ana sponsor önerilir. Sektörel münhasırlık, kullanım süresi ve tanıtım hakları ayrıca belirlenir; festivalin adı korunur.'},
  {id:'akademi',group:'program',title:'Akademi ve genç yetenek',summary:'Ücretsiz öğrenme ve üretim için yıl boyu destek.',companies:['isbank'],contribution:['Nakdi','Eğitim desteği'],period:'Yıl boyu Akademi takvimi',covers:['Eğitmen, atölye materyali, eğitim mekânı ve uygulama giderleri.','Senaryo, çekim ve kurgu çalışmalarında gençlerin ücretsiz katılımı.'],benefits:['Akademi sayfası, atölye duyuruları ve program raporunda sponsor alanı.','Eğitim ekibinin onayıyla deneyim paylaşımı veya meslek buluşması.','Yıl sonunda atölye ve katılımcı sayılarını içeren toplu sonuç raporu.'],measure:'Gerçekleşen atölyeler, katılım ve tamamlanan üretim çalışmaları.',note:'Eğitmen ve katılımcı seçimleri Akademi ekibinin sorumluluğunda kalır.'},
  {id:'frigya',group:'program',title:'Frigya Rotası ve gezici sinema',summary:'Üretimi ve gösterimleri Eskişehir’in ilçelerine taşıyan destek.',companies:['ford'],contribution:['Nakdi','Araç / ulaşım hizmeti'],period:'Rota çalışmaları, festival haftası ve gezici gösterimler',covers:['Çekim ekiplerinin, konukların ve gösterim ekipmanının ulaşım giderleri.','İlçe gösterimleri için saha kurulumu, yerel koordinasyon ve lojistik.'],benefits:['Frigya Rotası sayfası ve ilgili ilçe duyurularında sponsor alanı.','Onaylanan araç ve gösterim noktalarında hizmete bağlı görünürlük.','Rota ve gösterim sonuçlarının toplu raporlanması.'],measure:'Gerçekleşen rota günleri, transferler, ilçe gösterimleri ve izleyici sayısı.',note:'Araç türü, sürücü, yakıt, güzergâh ve hizmet günleri kapsamda ayrı ayrı netleştirilir.'},
  {id:'odul',group:'program',title:'Ödüller ve tören',summary:'Lületaşı ustalığını ve genç sinemacıların başarısını görünür kılan destek.',companies:['sarar'],contribution:['Nakdi','Ayni / tekstil'],period:'Ödül üretimi, kapanış töreni ve sonuç duyuruları',covers:['Planlanan lületaşı ödüllerinin üretimi, ustalık emeği ve sunum giderleri.','Tören organizasyonu ve ihtiyaç doğrultusunda tören ekibinin kıyafetleri.'],benefits:['Ödüller bölümünde ve tören teşekkür alanında sponsor düzeyiyle görünürlük.','Mutabık kalınan tören davetleri ve ödül üretim hikâyesinde destekçi anımı.'],measure:'Üretilen ödüller, gerçekleşen tören ve belgelenen tanıtım alanları.',note:'Projedeki ödüllerin adları ve bağımsız karar süreçleri korunur. Bu örnekte belirlenmiş bir nakit ödül tutarı yoktur.'},
  {id:'teknik',group:'service',title:'Kamera ve teknik üretim',summary:'Genç sinemacıların ekipmana erişimini kolaylaştıran destek.',companies:['canon'],contribution:['Ekipman ödüncü','Teknik uzmanlık'],period:'Belirlenecek Akademi atölyeleri ve çekim günleri',covers:['Kamera ve lens setleri, uygulamalı tanıtım ve teknik danışmanlık.','Ekipmanın teslim, kurulum ve kullanım desteği.'],benefits:['Teknik partnerler listesi ve desteklenen atölyelerde görünürlük.','Atölye yürütücüsünün onayıyla uygulamalı ürün deneyimi.'],measure:'Ekipmanın kullanıldığı günler ve desteklenen atölyeler.',note:'Ödünç süresi, cihaz adedi, teslim ve iade koşulları ayrıca belirlenir; cihaz bağışı varsayılmaz.'},
  {id:'dijital',group:'service',title:'Dijital deneyim ve erişilebilirlik',summary:'Bağlantı ve içeriğe erişim ihtiyaçlarını karşılayan destek.',companies:['turkcell'],contribution:['Hizmet','Nakdi'],period:'Festival hazırlığı, etkinlik günleri ve dijital arşiv dönemi',covers:['Etkinlik alanında internet, ekip iletişimi ve dijital yayın altyapısı.','İzinli içeriklerde altyazı ve erişilebilir yayın hizmetlerinin giderleri.'],benefits:['Dijital partnerler listesi ve desteklenen yayınların teşekkür alanında görünürlük.','Teknoloji ve erişilebilirlik katkısının sonuç raporunda yer alması.'],measure:'Sağlanan hizmet günleri ve erişilebilir hâle getirilen içerikler.',note:'Film gösterim ve çevrimiçi yayın hakları ayrıca alınır. Sponsor erişimi kişisel başvuru verilerini kapsamaz.'},
  {id:'konaklama',group:'service',title:'Konaklama ve konuk ağırlama',summary:'Konuk sinemacı, eğitmen ve jüri üyeleri için şehirde bir buluşma noktası.',companies:['tasigo'],contribution:['Oda tahsisi','Hizmet / indirim'],period:'Festival haftası ve mutabık kalınan eğitim günleri',covers:['Planlanan konuklar için oda-gece, kahvaltı ve ihtiyaç hâlinde toplantı alanı.','Konuk karşılama ve programla uyumlu rezervasyon koordinasyonu.'],benefits:['Konaklama partnerleri listesi ve konuk bilgilendirmelerinde görünürlük.','Desteklenen buluşmada ev sahibi olarak anılma.'],measure:'Sağlanan oda-gece ve kullanılan toplantı hizmetleri.',note:'Oda tipi, sayı, tarih, ücretsiz veya indirimli kullanım koşulları ayrıca netleştirilir.'},
  {id:'mekan',group:'service',title:'Mekân ve şehir içi görünürlük',summary:'Festivali gündelik şehir yaşamıyla buluşturan alan desteği.',companies:['espark'],contribution:['Mekân','Tanıtım alanı'],period:'Başvuru duyuruları ve festival dönemi',covers:['İzinleri ve uygunluğu netleştirilecek tanıtım, buluşma veya gösterim alanı.','Dijital ekranlar ve ortak alanlarda festival duyuruları.'],benefits:['Mekân partnerleri listesi ve o mekândaki etkinlik duyurusunda görünürlük.','Onaylanan programda ev sahibi olarak anılma.'],measure:'Kullanılan alan-gün, yayınlanan duyurular ve gerçekleşen etkinlikler.',note:'Espark bu demoda kesinleşmiş bir gösterim mekânı değildir. Teknik uygunluk, kapasite ve işletme izni ayrıca değerlendirilir.'},
  {id:'ikram',group:'service',title:'İkram ve gönüllü buluşmaları',summary:'Atölye aralarını ve festival ekibinin günlük ihtiyaçlarını destekleyen katkı.',companies:['kahve'],contribution:['Ürün','Servis hizmeti'],period:'Festival haftası ve seçilen atölye günleri',covers:['Ekip ve katılımcılar için belirlenecek sayıda içecek ve ikram.','Mola alanı kurulumu ve servis desteği.'],benefits:['İkram noktasında marka alanı ve hizmet partnerleri listesinde görünürlük.','Organizasyonca onaylanmış ürün deneyimi.'],measure:'Teslim edilen ürün / porsiyon ve desteklenen etkinlik günleri.',note:'Menü, porsiyon sayısı, servis saatleri ve beslenme ihtiyaçları önceden belirlenir.'},
  {id:'medya',group:'media',title:'Yerel ve ulusal medya',summary:'Başvuru çağrısını ve programı ilgili izleyicilerle buluşturan destek.',companies:['eskisehirnet','beyazperde'],contribution:['Reklam alanı','Duyuru desteği'],period:'Başvuru çağrısından sonuç duyurularına',covers:['Yerel izleyiciye ve Türkiye’deki sinemacılara yönelik program duyuruları.','Mutabık kalınan dijital reklam alanları ve etkinlik takvimi görünürlüğü.'],benefits:['Medya partnerleri bölümünde yer alma ve basın buluşmalarına erişim.','Basın materyallerine ve görüşme organizasyonuna editoryal bağımsızlıkla erişim.'],measure:'Gerçekleşen duyuru yerleşimleri ve yayıncı tarafından raporlanan erişim.',note:'Olumlu haber, eleştiri veya röportaj yayımlama taahhüdü varsayılmaz; yayıncının editoryal kararı bağımsızdır.'},
];

export const sponsorResearch = [
  {name:'İstanbul Film Festivali / İKSV',finding:'Festival, atölye, ödül, konaklama, mekân, medya ve servis desteği ayrı başlıklarda yer alıyor. İKSV’nin program açıklaması, tema desteğini ilgili gösterimlerde görünürlükle ilişkilendiriyor.',adaptation:'EGFF’de genel bütçe desteğini program ve hizmet ihtiyaçlarından ayırdık.',links:[{label:'Festival destekçileri',url:'https://film.iksv.org/tr/destekciler'},{label:'Sponsorluk kapsamları',url:'https://www.iksv.org/en/sponsorship-programme/sponsors-of-iksv'}]},
  {name:'Berlinale / Berlinale Talents',finding:'Ana ortaklıkta festival genelinde görünürlük ve ağırlama hakları bulunuyor. Talents ise ana ortak, eş ortak ve destekçi düzeylerinde eğitim ve buluşma programlarına ayrı kapsamlar sunuyor.',adaptation:'Ana sponsor görünürlüğünü geniş; Akademi desteğini kendi programıyla sınırlı kurguladık.',links:[{label:'Berlinale ana ortaklık',url:'https://b2b.berlinale.de/en/partner/postings/56-principal-partner'},{label:'Talents ortaklık modeli',url:'https://www.berlinale-talents.de/bt/page/c/become-a-partner'}]},
  {name:'Sundance Film Festival 2026',finding:'2026 duyurusunda presenting, leadership, sustaining ve media katmanları kullanılıyor; katkıların festival giderlerini ve yıl boyu sanatçı programlarını desteklediği belirtiliyor.',adaptation:'Edisyon desteği, yıl boyu eğitim ve medya katkısını ayrı değerlendirdik; yabancı paket bedellerini taşımadık.',links:[{label:'2026 festival duyurusu ve destekçiler',url:'https://www.sundance.org/blogs/2026-sundance-film-festival-unveils-97-projects-selected-for-the-feature-film-and-episodic-program/'}]},
];

export const sponsorDemoNotice = 'Bu sayfadaki firmalar DEMO SPONSOR örnekleridir. Yerleşimleri gerçek sponsorluk, firma onayı, görüşme veya taahhüt bulunduğunu ifade etmez. Eşleştirmeler, kamuya açık faaliyet bilgilerine dayanan önerilerdir.';

export function companiesFor(area:SponsorArea){return area.companies.map(id=>sponsorCompanies.find(company=>company.id===id)!);}
