'use client';
import {useState} from 'react';
import {eventSources} from '@/lib/events/sources';
import {eventVenues} from '@/lib/events/venues';
import {categoryLabels} from '@/lib/events/copy';
import {socialApi} from '@/lib/social/client';
import {useEvents} from '@/lib/events/client';
import type {CityEvent} from '@/lib/events/types';
export function EventsAdmin(){
 const {catalog,refresh}=useEvents(),[source,setSource]=useState('ebb'),[editing,setEditing]=useState<CityEvent|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function submit(form:HTMLFormElement){setBusy(true);setNotice('');const data=new FormData(form),venue=eventVenues.find(v=>v.id===data.get('venueId'));
  const event={id:editing?.id??'reviewed-'+crypto.randomUUID(),title:String(data.get('title')),category:String(data.get('category')),district:venue?.district??eventSources.find(s=>s.id===source)!.district,date:data.get('date')||null,time:data.get('time')||null,endTime:data.get('endTime')||null,venue:venue?.name??String(data.get('venue')),venueId:venue?.id??null,organizer:eventSources.find(s=>s.id===source)!.name,sourceId:source,sourceUrl:String(data.get('sourceUrl')),status:String(data.get('status')),price:String(data.get('price')),bookingUrl:null,summary:String(data.get('summary')),checkedAt:new Date().toISOString(),family:null,indoor:null};
  try{await socialApi('/admin/events','PUT',{sourceId:source,events:[event]});setNotice('Doğrulanmış kayıt yayımlandı. İptal ve erteleme bilgisi rota kontrollerine de uygulanır.');await refresh();setEditing(null);form.reset();}catch{setNotice('Kayıt yayımlanamadı. Kurum bağlantısını, alanları ve yönetici yetkisini kontrol edin.');}finally{setBusy(false);}
 }
 return <details className="sc-panel ev-admin"><summary>Şehir etkinliklerini yönet</summary><p>Ortak takvim sunmayan kurumların resmî duyurularını doğrulayarak ekleyin. Saat veya mekân bilinmiyorsa alanı boş bırakın; ziyaretçilere duyuru olarak gösterilir.</p><label>Kurum<select value={source} onChange={e=>{setSource(e.target.value);setEditing(null);}}>{eventSources.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Düzenlenecek kayıt<select value={editing?.id??''} onChange={e=>setEditing(catalog.events.find(x=>x.id===e.target.value)??null)}><option value="">Yeni etkinlik</option>{catalog.events.filter(e=>e.sourceId===source).map(e=><option value={e.id} key={e.id}>{e.date??'Tarih bekleniyor'} · {e.title}</option>)}</select></label>
 <form key={`${source}:${editing?.id??'new'}`} onSubmit={e=>{e.preventDefault();void submit(e.currentTarget);}}><label>Etkinlik adı<input name="title" required maxLength={200} defaultValue={editing?.title}/></label><label>Tür<select name="category" defaultValue={editing?.category??'concert'}>{Object.entries(categoryLabels('tr')).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><div className="ev-admin-time"><label>Tarih<input type="date" name="date" defaultValue={editing?.date??''}/></label><label>Başlangıç<input type="time" name="time" defaultValue={editing?.time??''}/></label><label>Bitiş · açıklanmışsa<input type="time" name="endTime" defaultValue={editing?.endTime??''}/></label></div><label>Rota için doğrulanmış mekân<select name="venueId" defaultValue={editing?.venueId??''}><option value="">Rota konumu henüz doğrulanmadı</option>{eventVenues.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><label>Diğer mekân / açıklama<input name="venue" maxLength={240} defaultValue={editing?.venue??''}/></label><label>Resmî duyuru bağlantısı<input type="url" name="sourceUrl" required defaultValue={editing?.sourceUrl} placeholder={eventSources.find(s=>s.id===source)!.url}/></label><label>Durum<select name="status" defaultValue={editing?.status??'scheduled'}><option value="scheduled">Tarihli etkinlik</option><option value="announced">Ön duyuru / başvuru</option><option value="cancelled">İptal</option><option value="postponed">Ertelendi</option></select></label><label>Giriş<select name="price" defaultValue={editing?.price??'unknown'}><option value="unknown">Açıklanmadı</option><option value="free">Ücretsiz</option><option value="paid">Ücretli</option></select></label><label>Kısa açıklama<textarea name="summary" maxLength={600} rows={3} defaultValue={editing?.summary}/></label><label className="ev-admin-check"><input required type="checkbox"/>Duyuruyu kurum kaynağından kontrol ettim; tarih, saat, yer ve durum bilgileri doğru.</label><button className="ev-primary" disabled={busy} type="submit">{busy?'Kaydediliyor…':'Doğrulanmış kaydı yayımla'}</button></form>{notice&&<p role="status">{notice}</p>}</details>;
}
