import Link from "next/link";
import { Building2,Film,Compass,FileText,Mail,ChevronRight,ShieldCheck } from "lucide-react";
import { text as t,type Locale } from "@/lib/routing/types";
import { qrCopy } from "@/lib/qr/copy";
const lead=t("Eskişehir Valiliği öncülüğünde; 14 ilçede turizm altyapısını, kültürel mirası ve yerel ekonomiyi ortak bir gelecek için buluşturan Vizyon Eskişehir 2036 projesi.","An Eskişehir Vision 2036 project led by the Governorship, bringing tourism infrastructure, cultural heritage and local economies together across 14 districts.","Ein Projekt der Vision Eskişehir 2036 unter Leitung des Gouverneursamts, das Tourismusinfrastruktur, Kulturerbe und lokale Wirtschaft in 14 Bezirken verbindet.","Un projet Vision Eskişehir 2036, sous la direction du Gouvernorat, associant infrastructures touristiques, patrimoine et économie locale dans 14 districts.","مشروع رؤية إسكي شهير 2036 بقيادة الولاية يجمع البنية السياحية والتراث والاقتصاد المحلي في 14 مقاطعة.");
export function MobileInstitution({locale="tr"}:{locale?:Locale}){
 const c=qrCopy(locale),base=locale==="tr"?"":`/${locale}`;
 const links=[
  {Icon:Building2,title:t("Amaç ve yönetim","Purpose & governance","Auftrag & Leitung","Mission & gouvernance","الهدف والإدارة"),hint:t("Valilik öncülüğü, ortak kamu kapasitesi","Governorship leadership and shared public capacity","Gouverneursamt und gemeinsame öffentliche Aufgaben","Gouvernorat et capacité publique partagée","قيادة الولاية والقدرات العامة المشتركة"),href:locale==="tr"?"/kurumsal":`${base}#institution`},
  {Icon:Film,title:t("Projeler ve programlar","Projects & programmes","Projekte & Programme","Projets & programmes","المشروعات والبرامج"),hint:t("Film, akademi, spor ve turizm altyapısı","Film, academy, sports and tourism infrastructure","Film, Akademie, Sport und Tourismusinfrastruktur","Cinéma, académie, sport et infrastructures","السينما والأكاديمية والرياضة والبنية السياحية"),href:locale==="tr"?"/projeler":`${base}#programmes`},
  {Icon:Compass,title:t("14 ilçeyi tanı","Meet the 14 districts","14 Bezirke entdecken","Découvrir les 14 districts","تعرّف إلى المقاطعات الـ14"),hint:t("Her ilçenin turizmdeki rolü","Each district’s tourism role","Die touristische Rolle jedes Bezirks","Le rôle touristique de chaque district","الدور السياحي لكل مقاطعة"),href:locale==="tr"?"/ilceler":`${base}#heritage`},
  {Icon:ShieldCheck,title:t("Vizyon Eskişehir 2036","Eskişehir Vision 2036","Vision Eskişehir 2036","Vision Eskişehir 2036","رؤية إسكي شهير 2036"),hint:t("12. Kalkınma Planı ile uyum","Alignment with the 12th Development Plan","Abstimmung mit dem 12. Entwicklungsplan","Cohérence avec le 12e Plan de développement","التوافق مع خطة التنمية الثانية عشرة"),href:locale==="tr"?"/kurumsal#kalkinma-plani":`${base}#impact`},
  {Icon:FileText,title:t("Birlik tüzüğü","Union charter · Türkçe","Satzung · Türkçe","Statuts · Türkçe","النظام الأساسي · Türkçe"),hint:t("İncelemeye sunulan taslak metin","Draft for review","Entwurf zur Prüfung","Projet soumis à examen","مسودة للمراجعة"),href:"/tuzuk"},
  {Icon:Mail,title:t("İletişim","Contact · Türkçe","Kontakt · Türkçe","Contact · Türkçe","التواصل · Türkçe"),hint:t("İl Sosyal Etüt ve Proje Müdürlüğü","Provincial Directorate of Social Studies and Projects","Provinzdirektion für Sozialstudien und Projekte","Direction provinciale des études sociales et des projets","المديرية الإقليمية للدراسات الاجتماعية والمشروعات"),href:"/iletisim"},
 ];
 return <main id="ana-icerik" className="app-institution-hub" lang={locale} dir={locale==="ar"?"rtl":"ltr"}><span className="qr-eyebrow">VİZYON ESKİŞEHİR 2036</span><h1>{c.institution}</h1><p>{lead[locale]}</p><div>{links.map(({Icon,title,hint,href})=><Link href={href} key={href}><span className="qr-row-icon"><Icon size={21}/></span><span><strong>{title[locale]}</strong><small>{hint[locale]}</small></span><ChevronRight size={18}/></Link>)}</div></main>;
}
