import { BusFront, TrainFront, ChevronDown, ExternalLink, Footprints } from "lucide-react";
import { clock } from "@/lib/routing/engine";
import { busLabel, departures, districtBusRecords, serviceGroup, transitDateAge, transitMapUrl } from "@/lib/routing/transit";
import { TRANSIT_CHECKED_ON, BUS_SOURCE, TRAM_SOURCE, ESTRAM_MOBILE_SOURCE } from "@/lib/routing/transit-data";
import { transitCopy } from "@/lib/routing/transit-copy";
import type { Leg, Locale, Preferences } from "@/lib/routing/types";

export function TransitJourneyCard({ leg, locale, returning = false }: { leg: Leg; locale: Locale; returning?: boolean }) {
  const journey=leg.transit, c=transitCopy(locale);
  if (!journey) return null;
  return <details className="rp-transit-leg"><summary><BusFront size={17} aria-hidden="true"/><span><strong>{journey.rides.map(r => `${c[r.vehicle]} ${r.line}`).join(" → ")}</strong><small>{returning ? c.return : c.details} · {Math.max(0,journey.rides.length-1)} {c.transfer}</small></span><ChevronDown size={16} aria-hidden="true"/></summary><div className="rp-transit-steps">{journey.rides.map((r,i) => <div key={`${r.line}-${i}`} className="rp-transit-ride"><strong>{r.vehicle === "tram" ? <TrainFront size={16} aria-hidden="true"/> : <BusFront size={16} aria-hidden="true"/>}{c.line} {r.line} · {r.direction}</strong><p><b>{r.estimatedBoard ? "~" : ""}{clock(r.depart)}</b> {c.board}: {r.board}{r.estimatedBoard && <small> · {c.estimate}</small>}</p><p><b>~{clock(r.arrive)}</b> {c.alight}: {r.alight} <small>· {c.estimate}</small></p><p className="rp-small-note">{r.terminalDeparture !== undefined ? `${c.terminal}: ${r.terminal} · ${clock(r.terminalDeparture)}` : `${c.frequency}: ${r.headway} min`}</p><div><a href={r.source} target="_blank" rel="noreferrer">{c.source} ↗</a><a href={transitMapUrl(r)} target="_blank" rel="noreferrer">Google Maps ↗</a></div></div>)}<p><Footprints size={15} aria-hidden="true"/> {c.walking}: ~{journey.walkingMinutes} min · ~{journey.walkingKm} km</p><p>{c.waiting}: {journey.waitingMinutes} min</p></div></details>;
}
export function TransitCoverage({ preferences: p, locale }: { preferences: Preferences; locale: Locale }) {
  const c=transitCopy(locale), records=districtBusRecords(p.districts);
  return <div className="rp-transit-information"><p className="rp-small-note">{c.checked}: <time>{TRANSIT_CHECKED_ON}</time> · {p.date ? c[serviceGroup(p.date,p.transitHoliday)] : c.needDate}</p><p>{c.snapshot}</p>{p.date && Math.abs(transitDateAge(p.date))>30 && <p className="rp-transit-alert">{c.future}</p>}<details className="rp-transit-coverage"><summary>{c.coverage}<ChevronDown size={17} aria-hidden="true"/></summary><div><p>{c.coverageNote}</p>{records.map(r => <section key={r.id}><h4>{r.district} · {c.line} {busLabel(r)}</h4>{r.directions.map((d,i) => <p key={i}><strong>{d.terminal}</strong><span>{p.date ? departures(r,i,p.date,p.transitHoliday).map(clock).join(" · ") || c.noService : c.needDate}</span></p>)}{r.updated && <small>{c.updated}: {r.updated}</small>}<a href={r.source} target="_blank" rel="noreferrer">{c.source}<ExternalLink size={14} aria-hidden="true"/></a></section>)}<div className="rp-transit-source-links"><a href={BUS_SOURCE} target="_blank" rel="noreferrer">{c.bus} ↗</a><a href={TRAM_SOURCE} target="_blank" rel="noreferrer">{c.tram} ↗</a></div></div></details><a className="rp-transit-live-link" href={ESTRAM_MOBILE_SOURCE} target="_blank" rel="noreferrer">{c.live}<ExternalLink size={15} aria-hidden="true"/></a></div>;
}
