'use client';
import {EventsAdmin} from './events-admin';
import {useEffect,useState} from 'react';
import {ShieldCheck,Check,X,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {socialApi,SocialClientError,COMMUNITY_ORIGIN} from '@/lib/social/client';
import {useSocial} from './social-provider';
import {MediaViewer} from './social-feed';
import type {Media} from '@/lib/social/types';
interface Item{id:string;revision:number;title?:string;body?:string;name?:string;bio?:string;handle?:string;ai_state?:string;created_at:string;}
interface Queue{profiles:Item[];posts:Item[];comments:Item[];media:(Media&{post_id:string})[];reports:{id:string;reason:string;detail:string;target_type:string;target_id:string;target_title:string|null;target_body:string|null}[];}
export function SocialAdmin({signInPath}:{signInPath:string}){
 const {profile,loading:authLoading}=useSocial(),[queue,setQueue]=useState<Queue|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reviewed,setReviewed]=useState<Record<string,boolean>>({});
 async function load(){setError('');setBusy(true);try{setQueue(await socialApi<Queue>('/admin/queue'));setReviewed({});}catch(e){setError(e instanceof SocialClientError&&e.code==='forbidden'?'Bu alan yalnızca yetkilendirilmiş içerik yöneticilerine açıktır.':'İnceleme kuyruğuna ulaşılamadı. Yeniden deneyin.');}finally{setBusy(false);}}
 useEffect(()=>{if(profile?.admin)void load();},[profile?.id]);
 async function review(type:'profile'|'post'|'comment',item:Item,decision:'approved'|'rejected'){setBusy(true);setError('');try{await socialApi('/admin/review','POST',{type,id:item.id,revision:item.revision,decision,reviewedAllMedia:!!reviewed[item.id]});await load();}catch(e){setError(e instanceof SocialClientError&&e.code==='revision_changed'?'İçerik değişmiş. Güncel sürümü yeniden inceleyin.':'İşlem tamamlanmadı. İçeriği ve medya incelemesini kontrol edin.');}finally{setBusy(false);}}
 if(!profile?.admin)return <main className="sc-page" id="ana-icerik"><div className="sc-empty"><ShieldCheck size={34}/><h1>İçerik yönetimi</h1><p>{authLoading?'Yetki kontrol ediliyor…':'Bu alan, kurumun yetkilendirdiği yönetici hesabıyla kullanılır.'}</p><p>Yönetici yetkisi, ziyaretçi profili oluşturarak veya ortak demo şifresiyle edinilemez.</p><a className="app-primary" href={COMMUNITY_ORIGIN+signInPath} target="_top">Yetkili hesapla giriş yap</a></div></main>;
 const groups=[['profiles','profile','Profiller'],['posts','post','Rotalar'],['comments','comment','Yorumlar']] as const;
 return <main className="sc-page" id="ana-icerik"><header className="sc-page-heading sc-heading-actions"><div><span className="sc-eyebrow">İÇERİK İNCELEME</span><h1>Yayın öncesi kontrol</h1><p>Metni, rota bağlamını ve tüm dosyaları inceleyin. Otomatik kontrol sonucu, yayın onayı değildir.</p></div><Button variant="outline" disabled={busy} onClick={load} aria-label="Yenile"><RefreshCw size={20}/></Button></header>{error&&<p className="sc-error" role="alert">{error}</p>}<EventsAdmin/><Tabs defaultValue="posts"><TabsList className="sc-tabs">{groups.map(([key,,label])=><TabsTrigger key={key} value={key}>{label} · {queue?.[key].length??0}</TabsTrigger>)}<TabsTrigger value="reports">Bildirimler · {queue?.reports.length??0}</TabsTrigger></TabsList>{groups.map(([key,type])=><TabsContent key={key} value={key}>{queue?.[key].map(item=>{const files=queue.media.filter(m=>m.post_id===item.id).map(m=>({...m,url:COMMUNITY_ORIGIN+'/api/community/media/'+m.id}));return <article className="sc-panel sc-review-item" key={item.id}><small>{new Date(item.created_at).toLocaleString('tr-TR')}</small><h2>{item.title??item.name??'Yorum'}</h2>{item.handle&&<p>@{item.handle}</p>}<p className="sc-post-story">{item.body??item.bio}</p>{type==='post'&&<p className="sc-meta">Otomatik kontrol: {item.ai_state==='clear'?'işaretleme yok':item.ai_state==='flagged'?'inceleme gerekli':'yapay zekâ kontrolü kullanılamıyor'}</p>}{files.length>0&&<><MediaViewer media={files} locale="tr"/><label className="sc-checkbox"><Checkbox checked={!!reviewed[item.id]} onCheckedChange={v=>setReviewed({...reviewed,[item.id]:v===true})}/><span>Tüm fotoğraf ve videoları, açıklamalarını ve görünen kişisel bilgileri inceledim.</span></label></>}<div className="sc-detail-actions"><Button disabled={busy||files.length>0&&!reviewed[item.id]} onClick={()=>review(type,item,'approved')}><Check size={17}/>Yayımla</Button><Button variant="outline" disabled={busy} onClick={()=>review(type,item,'rejected')}><X size={17}/>Düzenleme iste</Button></div></article>;})}{queue&&!queue[key].length&&<p className="sc-empty">Bekleyen içerik yok.</p>}</TabsContent>)}<TabsContent value="reports">{queue?.reports.map(report=><article key={report.id} className="sc-panel"><h2>{report.reason}</h2><p>{report.detail}</p><details className="sc-report-content"><summary>Bildirilen içeriği incele</summary><h3>{report.target_title}</h3><p className="sc-post-story">{report.target_body??'İçerik artık mevcut değil.'}</p></details><div className="sc-detail-actions">{[true,false].map(remove=><Button key={String(remove)} variant={remove?'default':'outline'} disabled={busy} onClick={async()=>{setBusy(true);try{await socialApi('/admin/report','POST',{id:report.id,removeContent:remove});await load();}catch{setError('Bildirim işlenemedi.');}finally{setBusy(false);}}}>{remove?'İçeriği kaldır':'Bildirimi kapat'}</Button>)}</div></article>)}</TabsContent></Tabs></main>;
}
