'use client';
import {useState,useEffect} from 'react';
import Link from 'next/link';
import {ImagePlus,X,Check,Route} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {readTrips,type Trip} from '@/lib/mobile/trips';
import {demoCopy} from '@/lib/social/demo-copy';
import {socialCopy,socialError} from '@/lib/social/copy';
import {socialApi,socialFetch,preparePhoto,SocialClientError} from '@/lib/social/client';
import {screenText} from '@/lib/social/moderation';
import type {Locale,Plan,Preferences} from '@/lib/routing/types';
import {useSocial} from './social-provider';
import {AuthDialog} from './social-auth';
type Attachment={file:File;caption:string;uploaded:boolean;id:string};
export function SocialComposer({open,onOpenChange,locale,onCreated,initial}:{open:boolean;onOpenChange:(v:boolean)=>void;locale:Locale;onCreated?:(id:string)=>void;initial?:{plan:Plan;preferences:Preferences;title:string}}){
 const c=socialCopy(locale),base=locale==='tr'?'':`/${locale}`,{profile,status}=useSocial(),[trips,setTrips]=useState<Trip[]>([]),[selected,setSelected]=useState(''),[title,setTitle]=useState(''),[body,setBody]=useState(''),[files,setFiles]=useState<Attachment[]>([]),[accept,setAccept]=useState(false),[rights,setRights]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[created,setCreated]=useState(''),[auth,setAuth]=useState(false);
 useEffect(()=>{if(open&&!created){const entries=readTrips();setTrips(entries);setSelected(entries[0]?.id??'');setTitle(initial?.title??entries[0]?.title??'');}},[open]);
 const chosen=initial??trips.find(t=>t.id===selected);
 async function chooseFiles(list:FileList|null){if(!list)return;setError('');const incoming=Array.from(list);if(incoming.length+files.length>6){setError(c.mediaHint);return;}setBusy(true);try{const ready:Attachment[]=[];for(const file of incoming){if(!['image/jpeg','image/png','image/webp','video/mp4','video/webm'].includes(file.type)||file.size>(file.type.startsWith('image/')?8:25)*1024*1024)throw new SocialClientError('unsupported_media');ready.push({file:await preparePhoto(file),caption:'',uploaded:false,id:crypto.randomUUID()});}setFiles(old=>[...old,...ready]);}catch(e){setError(socialError(e instanceof SocialClientError?e.code:'unsupported_media',locale));}finally{setBusy(false);}}
 async function submit(e:React.FormEvent){e.preventDefault();if(!profile){setAuth(true);return;}if(!chosen)return;if(!accept||files.length&&!rights){setError(c.rulesAccept);return;}const filtered=screenText(title+' '+body+' '+files.map(f=>f.caption).join(' '));if(!filtered.ok){setError(socialError(filtered.reason!,locale));return;}setBusy(true);setError('');let id=created;
  try {if(!id){const result=await socialApi<{id:string}>('/posts','POST',{title,body,preferences:chosen.preferences,planId:chosen.plan.id,acceptedRules:true});id=result.id;setCreated(id);}for(const attachment of files.filter(f=>!f.uploaded)){await socialFetch('/posts/'+id+'/media',{method:'POST',headers:{'Content-Type':attachment.file.type,'X-Media-Caption':encodeURIComponent(attachment.caption)},body:attachment.file,signal:AbortSignal.timeout(120000)});setFiles(old=>old.map(f=>f.id===attachment.id?{...f,uploaded:true}:f));}onCreated?.(id);onOpenChange(false);setCreated('');setFiles([]);setBody('');setAccept(false);setRights(false);}catch(e){setError((id?c.uploadFailed+' ':'')+socialError(e instanceof SocialClientError?e.code:'service_unavailable',locale));}finally{setBusy(false);}
 }
 return <><Sheet open={open} onOpenChange={v=>{if(!busy)onOpenChange(v);}}><SheetContent side="bottom" className="sc-sheet" showCloseButton={false} dir={locale==='ar'?'rtl':'ltr'}><div className="sc-sheet-heading"><div><SheetTitle>{c.newPost}</SheetTitle><SheetDescription>{(status?.demoMode?demoCopy(locale).private:c.reviewNote)}</SheetDescription></div><Button variant="ghost" size="icon" aria-label={c.close} disabled={busy} onClick={()=>onOpenChange(false)}><X/></Button></div>{chosen?<form className="sc-form" onSubmit={submit}>{!initial&&<label>{c.chooseTrip}<select disabled={!!created||busy} value={selected} onChange={e=>{setSelected(e.target.value);setTitle(trips.find(t=>t.id===e.target.value)?.title??'');}}>{trips.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label>}<label>{c.postTitle}<Input value={title} onChange={e=>setTitle(e.target.value)} required minLength={3} maxLength={90} disabled={!!created}/></label><label>{c.postBody}<Textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={3000} rows={4} disabled={!!created}/></label><div className="sc-upload"><label className="sc-upload-button"><ImagePlus size={21}/><strong>{c.media}</strong><input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" multiple disabled={busy} onChange={e=>{void chooseFiles(e.target.files);e.target.value='';}}/></label><p className="sc-meta">{c.mediaHint}</p>{files.map(f=><div key={f.id} className="sc-attachment"><div><span>{f.file.type.startsWith('image/')?'▧':'▶'}</span><strong>{f.file.name}</strong>{f.uploaded?<Check size={19}/>:<Button type="button" variant="ghost" size="icon" disabled={busy} aria-label={c.delete} onClick={()=>setFiles(old=>old.filter(x=>x.id!==f.id))}><X size={18}/></Button>}</div><label>{c.caption}<Input value={f.caption} maxLength={160} disabled={f.uploaded||busy} onChange={e=>setFiles(old=>old.map(x=>x.id===f.id?{...x,caption:e.target.value}:x))}/></label></div>)}</div>{!!files.length&&<label className="sc-checkbox"><Checkbox checked={rights} onCheckedChange={v=>setRights(v===true)}/><span>{c.mediaRights}</span></label>}<label className="sc-checkbox"><Checkbox checked={accept} onCheckedChange={v=>setAccept(v===true)}/><span>{c.rulesAccept}</span></label>{error&&<p className="sc-error" role="alert">{error}</p>}<Button type="submit" disabled={busy}>{busy?c.loading:c.publish}</Button></form>:<div className="sc-empty"><Route size={32}/><p>{c.noTrip}</p><Link className="app-primary" href={`${base}/rotani-olustur`}>{c.adapt}</Link></div>}</SheetContent></Sheet><AuthDialog open={auth} onOpenChange={setAuth} locale={locale}/></>;
}
export function RouteSocialAction({plan,preferences,title,locale}:{plan:Plan;preferences:Preferences;title:string;locale:Locale}){const [open,setOpen]=useState(false);return <><button type="button" onClick={()=>setOpen(true)}><ImagePlus size={18}/>{socialCopy(locale).newPost}</button><SocialComposer open={open} onOpenChange={setOpen} locale={locale} initial={{plan,preferences,title}}/></>;}
