import type { Locale } from "@/lib/routing/types";

const copy = {
  tr: {
    title: "Eskişehir Cebimde", subtitle: "Rotalar, QR keşif ve etkinlikler ana ekranında.",
    install: "Uygulamayı kur", installing: "Kurulum açılıyor…", later: "Daha sonra", close: "Kapat",
    heading: "Eskişehir Cebimde uygulamasını kur", description: "Uygulama simgesinden Eskişehir’i keşfetmeye başla.",
    iosSteps: ["Safari’de Paylaş menüsünü aç. Gerekirse önce Diğer (…) düğmesine dokun.", "Ana Ekrana Ekle’yi seç. Görünmüyorsa Eylemleri Düzenle bölümünden ekle.", "Web Uygulaması Olarak Aç seçeneği görünüyorsa açık bırak ve Ekle’ye dokun."],
    androidSteps: ["Tarayıcının menüsünü aç (⋮).", "Uygulamayı yükle veya Ana ekrana ekle seçeneğini seç.", "Telefonundaki kurulum ekranında Yükle veya Ekle’ye dokun."],
    desktopSteps: ["Tarayıcının adres çubuğunda veya menüsünde uygulama kurma seçeneği varsa aç.", "Açılan kurulum ekranındaki adımları tamamla.", "Kurulum seçeneği yoksa uygulama bağlantısını telefonunda aç ve Uygulamayı kur’a dokun."],
    openDesktop: "Destekleyen tarayıcılarda uygulamayı bu bilgisayara kurabilirsin. Telefonuna kurmak için bu bağlantıyı telefonunda aç.",
    openSafari: "Bu bağlantıyı Safari’de açarak aşağıdaki adımları uygula.",
    openBrowser: "Bağlantıyı Chrome veya Samsung Internet’te açarak aşağıdaki adımları uygula.",
    copy: "Bağlantıyı kopyala", copied: "Kopyalandı", copyFallback: "Bağlantıya basılı tutup kopyalayabilirsin.", link: "Uygulama bağlantısı",
    done: "Anladım", error: "Kurulum ekranı açılamadı. Tarayıcı menüsünden ekleyebilirsin.",
  },
  en: {
    title: "Eskişehir Cebimde", subtitle: "Routes, QR discoveries and events on your home screen.",
    install: "Install app", installing: "Opening install…", later: "Later", close: "Close",
    heading: "Install Eskişehir Cebimde", description: "Start exploring Eskişehir from the app icon.",
    iosSteps: ["Open Share in Safari. You may need to tap More (…) first.", "Choose Add to Home Screen. If it is missing, enable it under Edit Actions.", "Keep Open as Web App on if shown, then tap Add."],
    androidSteps: ["Open your browser menu (⋮).", "Choose Install app or Add to Home screen.", "Confirm with Install or Add on your phone."],
    desktopSteps: ["If your browser offers an app installation option in its address bar or menu, open it.", "Complete the steps in the installation dialog.", "If installation is unavailable, open the app link on your phone and tap Install app."],
    openDesktop: "Supported browsers can install the app on this computer. To install it on your phone, open this link there.",
    openSafari: "Open this link in Safari, then follow these steps.", openBrowser: "Open this link in Chrome or Samsung Internet, then follow these steps.",
    copy: "Copy link", copied: "Copied", copyFallback: "Touch and hold the link to copy it.", link: "App link", done: "Got it", error: "The install dialog could not open. You can use your browser menu instead.",
  },
  de: {
    title: "Eskişehir Cebimde", subtitle: "Routen, QR-Entdeckungen und Veranstaltungen auf dem Home-Bildschirm.",
    install: "App installieren", installing: "Installation wird geöffnet…", later: "Später", close: "Schließen",
    heading: "Eskişehir Cebimde installieren", description: "Entdecke Eskişehir über das App-Symbol.",
    iosSteps: ["Öffne in Safari das Teilen-Menü, gegebenenfalls zuerst über Mehr (…).", "Wähle Zum Home-Bildschirm. Fehlt die Option, aktiviere sie unter Aktionen bearbeiten.", "Lass Als Web-App öffnen aktiviert, falls angezeigt, und tippe auf Hinzufügen."],
    androidSteps: ["Öffne das Browsermenü (⋮).", "Wähle App installieren oder Zum Startbildschirm hinzufügen.", "Bestätige auf deinem Telefon mit Installieren oder Hinzufügen."],
    desktopSteps: ["Falls dein Browser in der Adressleiste oder im Menü eine App-Installation anbietet, öffne sie.", "Folge den Schritten im Installationsfenster.", "Ist die Installation nicht verfügbar, öffne den App-Link auf deinem Telefon und tippe auf App installieren."],
    openDesktop: "Unterstützte Browser können die App auf diesem Computer installieren. Für die Installation auf deinem Telefon öffne diesen Link dort.",
    openSafari: "Öffne diesen Link in Safari und folge diesen Schritten.", openBrowser: "Öffne diesen Link in Chrome oder Samsung Internet und folge diesen Schritten.",
    copy: "Link kopieren", copied: "Kopiert", copyFallback: "Halte den Link gedrückt, um ihn zu kopieren.", link: "App-Link", done: "Verstanden", error: "Das Installationsfenster konnte nicht geöffnet werden. Nutze das Browsermenü.",
  },
  fr: {
    title: "Eskişehir Cebimde", subtitle: "Itinéraires, découvertes QR et événements sur votre écran d’accueil.",
    install: "Installer l’application", installing: "Ouverture de l’installation…", later: "Plus tard", close: "Fermer",
    heading: "Installer Eskişehir Cebimde", description: "Découvrez Eskişehir depuis l’icône de l’application.",
    iosSteps: ["Ouvrez le menu Partager de Safari, si nécessaire via Plus (…).", "Choisissez Sur l’écran d’accueil. Si l’option manque, activez-la dans Modifier les actions.", "Laissez Ouvrir comme app web activé si proposé, puis touchez Ajouter."],
    androidSteps: ["Ouvrez le menu du navigateur (⋮).", "Choisissez Installer l’application ou Ajouter à l’écran d’accueil.", "Confirmez avec Installer ou Ajouter sur votre téléphone."],
    desktopSteps: ["Si votre navigateur propose l’installation dans la barre d’adresse ou son menu, ouvrez cette option.", "Suivez les étapes de la fenêtre d’installation.", "Si l’installation n’est pas disponible, ouvrez le lien sur votre téléphone et touchez Installer l’application."],
    openDesktop: "Les navigateurs compatibles permettent l’installation sur cet ordinateur. Pour l’installer sur votre téléphone, ouvrez ce lien dessus.",
    openSafari: "Ouvrez ce lien dans Safari, puis suivez ces étapes.", openBrowser: "Ouvrez ce lien dans Chrome ou Samsung Internet, puis suivez ces étapes.",
    copy: "Copier le lien", copied: "Copié", copyFallback: "Appuyez longuement sur le lien pour le copier.", link: "Lien de l’application", done: "Compris", error: "La fenêtre d’installation ne s’est pas ouverte. Utilisez le menu du navigateur.",
  },
  ar: {
    title: "Eskişehir Cebimde", subtitle: "المسارات واكتشافات QR والفعاليات على شاشتك الرئيسية.",
    install: "تثبيت التطبيق", installing: "جارٍ فتح التثبيت…", later: "لاحقًا", close: "إغلاق",
    heading: "تثبيت Eskişehir Cebimde", description: "ابدأ استكشاف إسكي شهير من أيقونة التطبيق.",
    iosSteps: ["افتح قائمة المشاركة في Safari. قد تحتاج إلى الضغط على المزيد (…) أولًا.", "اختر إضافة إلى الشاشة الرئيسية. إذا لم تظهر، أضفها من تعديل الإجراءات.", "اترك فتح كتطبيق ويب مفعّلًا إن ظهر، ثم اضغط إضافة."],
    androidSteps: ["افتح قائمة المتصفح (⋮).", "اختر تثبيت التطبيق أو إضافة إلى الشاشة الرئيسية.", "أكّد بالضغط على تثبيت أو إضافة على الهاتف."],
    desktopSteps: ["إذا ظهر خيار تثبيت التطبيق في شريط العنوان أو قائمة المتصفح، افتحه.", "أكمل الخطوات في نافذة التثبيت.", "إذا لم يتوفر التثبيت، افتح الرابط على هاتفك واضغط تثبيت التطبيق."],
    openDesktop: "يمكن تثبيت التطبيق على هذا الكمبيوتر في المتصفحات المدعومة. لتثبيته على هاتفك، افتح هذا الرابط هناك.",
    openSafari: "افتح هذا الرابط في Safari ثم اتبع الخطوات التالية.", openBrowser: "افتح هذا الرابط في Chrome أو Samsung Internet ثم اتبع الخطوات التالية.",
    copy: "نسخ الرابط", copied: "تم النسخ", copyFallback: "اضغط مطولًا على الرابط لنسخه.", link: "رابط التطبيق", done: "فهمت", error: "تعذّر فتح نافذة التثبيت. يمكنك استخدام قائمة المتصفح.",
  },
};

export function installCopy(locale: Locale) { return copy[locale] ?? copy.tr; }
