import { text as t, type Place, type FoodArea, type RouteTheme, type Zone, type Localized, type Interest } from "./types";

export const CATALOG_VERSION = "2026-09-08.1";
export const VERIFIED_ON = "2026-09-08";
const ktb = (path: string) => `https://eskisehir.ktb.gov.tr/${path}`;
const see = "https://goturkiye.com/eskisehir/see";
const cuisine = ktb("TR-156622/eskisehir39de-yemek-kulturu.html");
const sivri = ktb("TR-362650/sivrihisar.html");
const frig = ktb("TR-158729/frig-vadilerinde-yuruyus-rotalari.html");
export const sources = [
  { name: "Eskişehir İl Kültür ve Turizm Müdürlüğü", url: "https://eskisehir.ktb.gov.tr/" },
  { name: "Eskişehir Büyükşehir Belediyesi · Bisiklet güzergâhı", url: "https://www.eskisehir.bel.tr/icerik-detay.php?cat_icerik=1&icerik_id=11755&menu_id=24" },
  { name: "GoTürkiye · Eskişehir mutfağı", url: "https://goturkiye.com/eskisehir/taste" },
  { name: "UNESCO · Ahşap direkli camiler", url: "https://whc.unesco.org/en/list/1694/" },
];
export const zoneNames: Record<Zone, string> = {
  center: "Eskişehir Gar / merkez", oldtown: "Odunpazarı", sazova: "Sazova", kentpark: "Kentpark", river: "Porsuk · Sümer",
  seyit: "Seyitgazi", doganli: "Doğanlı Vadisi", midas: "Yazılıkaya", han: "Han", sivri: "Sivrihisar",
  cifteler: "Çifteler", yunus: "Yunus Emre · Sarıköy", gurleyik: "Gürleyik", inonu: "İnönü",
};
export const urbanZones: Zone[] = ["center", "oldtown", "sazova", "kentpark", "river"];
export const origins: Zone[] = ["center", "oldtown", "sivri", "seyit", "midas", "cifteler", "inonu"];

// These are deliberately rounded editorial travel estimates, not a road-routing API or official kilometre measurements.
// A sparse corridor graph prevents straight-line shortcuts across mountains. See docs/AKILLI-ROTA.md.
export const roadEdges: [Zone, Zone, number][] = [
  ["center", "oldtown", 3.5], ["center", "sazova", 7], ["center", "kentpark", 5], ["center", "river", 4.5],
  ["oldtown", "river", 4], ["river", "sazova", 4.5], ["oldtown", "kentpark", 5],
  ["oldtown", "seyit", 43], ["seyit", "doganli", 27], ["doganli", "midas", 17], ["midas", "han", 20],
  ["seyit", "cifteler", 47], ["han", "cifteler", 45], ["center", "cifteler", 70],
  ["center", "sivri", 102], ["cifteler", "sivri", 57], ["sivri", "yunus", 43],
  ["center", "yunus", 98], ["yunus", "gurleyik", 75], ["center", "gurleyik", 125], ["center", "inonu", 40],
];
function place(id: string, name: string, zone: Zone, district: string, minutes: number, interests: Interest[], summary: Localized, source: string, extra: Partial<Place> = {}): Place {
  return { id, name, zone, district, minutes, interests, summary, source, status: "existing", walking: 0.6,
    indoor: false, family: true, lowWalk: true, paid: false, note: "hours", window: [540, 1020], ...extra };
}
export const places: Place[] = [
  place("porsuk", "Porsuk · Adalar", "center", "Tepebaşı", 55, ["city", "nature"], t("Nehir kıyısında kent yaşamı ve köprüler.", "Riverside life and bridges.", "Stadtleben und Brücken am Fluss.", "Vie urbaine et ponts au bord de l’eau.", "حياة المدينة والجسور على ضفاف النهر."), see, { note: "pedestrian", window: [480, 1140], walking: 1.2 }),
  place("doktorlar", "Doktorlar Caddesi", "center", "Tepebaşı", 35, ["city"], t("Yaya aksında heykeller ve sokak kültürü.", "Sculptures and street culture along the pedestrian axis.", "Skulpturen und Straßenkultur in der Fußgängerzone.", "Sculptures et culture de rue sur l’axe piéton.", "منحوتات وثقافة الشارع على محور المشاة."), "https://eskisehir.ktb.gov.tr/", { note: "pedestrian", window: [480, 1140] }),
  place("haller", "Haller Gençlik Merkezi", "center", "Tepebaşı", 40, ["city", "taste"], t("Eski hal yapısında sosyal yaşam ve mola.", "A social stop in a converted market hall.", "Pause im umgenutzten historischen Marktgebäude.", "Une pause dans les anciennes halles.", "استراحة في مبنى السوق التاريخي المعاد استخدامه."), "https://www.eskisehir.bel.tr/sayfalar.php?sayfalar_id=57", { indoor: true, window: [600, 1080] }),
  place("tasbasi", "Taşbaşı Çarşısı", "center", "Odunpazarı", 45, ["craft", "taste", "city"], t("Çarşı kültürü, yerel ürünler ve esnaf.", "Market culture, local products and independent shops.", "Marktkultur, lokale Produkte und kleine Geschäfte.", "Culture du marché, produits locaux et artisans.", "ثقافة السوق والمنتجات المحلية والمتاجر الصغيرة."), see, { window: [600, 1020] }),
  place("hamamyolu", "Hamamyolu", "oldtown", "Odunpazarı", 40, ["city", "nature"], t("Yaya odaklı kamusal alanda sakin yürüyüş.", "A gentle walk through a pedestrian public space.", "Ein ruhiger Spaziergang im öffentlichen Fußgängerbereich.", "Promenade tranquille dans un espace public piéton.", "نزهة هادئة في فضاء عام مخصص للمشاة."), see, { window: [480, 1140], note: "pedestrian", walking: 0.9 }),
  place("odunpazari", "Odunpazarı Tarihî Sokakları", "oldtown", "Odunpazarı", 65, ["heritage", "city"], t("Sivil mimariyi sokak ölçeğinde keşfedin.", "Explore traditional domestic architecture on foot.", "Traditionelle Wohnarchitektur zu Fuß entdecken.", "Découvrir l’architecture domestique à pied.", "اكتشاف العمارة السكنية التقليدية سيراً."), ktb("TR-149989/odunpazari.html"), { note: "uneven", lowWalk: false, walking: 1.4 }),
  place("kursunlu", "Kurşunlu Külliyesi", "oldtown", "Odunpazarı", 50, ["heritage", "faith"], t("Osmanlı külliyesi ve avlu düzeni.", "An Ottoman religious complex and courtyard.", "Osmanischer Baukomplex mit Innenhof.", "Un ensemble ottoman et sa cour.", "مجمع عثماني وفناؤه."), see, { note: "worship" }),
  place("atlihan", "Atlıhan El Sanatları Çarşısı", "oldtown", "Odunpazarı", 45, ["craft", "heritage"], t("Lületaşı işçiliği ve yerel ustaların ürünleri.", "Meerschaum craftsmanship and local makers.", "Meerschaumkunst und lokale Handwerker.", "Artisanat de l’écume de mer et créateurs locaux.", "حرف حجر الإسفنج ومنتجات الحرفيين المحليين."), see, { indoor: true, window: [600, 1020] }),
  place("eti", "ETİ Arkeoloji Müzesi", "oldtown", "Odunpazarı", 80, ["heritage"], t("Eskişehir’in arkeolojik birikimine bütünlüklü bakış.", "An overview of Eskişehir’s archaeological heritage.", "Überblick über Eskişehirs archäologisches Erbe.", "Panorama du patrimoine archéologique d’Eskişehir.", "نظرة شاملة على التراث الأثري لإسكي شهير."), ktb("TR-339469/eti-arkeoloji-muzesi-odunpazari.html"), { indoor: true, paid: true }),
  place("cam", "Çağdaş Cam Sanatları Müzesi", "oldtown", "Odunpazarı", 50, ["craft", "city"], t("Camın çağdaş sanatla buluşması.", "Glass meets contemporary art.", "Glas trifft zeitgenössische Kunst.", "Le verre rencontre l’art contemporain.", "لقاء الزجاج بالفن المعاصر."), "https://www.eskisehir.bel.tr/sayfalar.php?sayfalar_id=58", { indoor: true, paid: true, closedDays: [1], window: [600, 1020] }),
  place("balmumu", "Balmumu Heykeller Müzesi", "oldtown", "Odunpazarı", 60, ["city", "heritage"], t("Portreler üzerinden kültür ve yakın tarih.", "Culture and recent history through portraits.", "Kultur und Zeitgeschichte anhand von Porträts.", "Culture et histoire récente à travers les portraits.", "الثقافة والتاريخ الحديث من خلال الشخصيات."), ktb("TR-340164/yilmaz-buyukersen-balmumu-heykeller-muzesi-odunpazari.html"), { indoor: true, paid: true, closedDays: [1], window: [600, 1020] }),
  place("kentbellegi", "Kent Belleği Müzesi", "oldtown", "Odunpazarı", 45, ["city", "heritage"], t("Kentin hafızasına ayrılan bir müze durağı.", "A museum stop dedicated to the city’s memory.", "Ein Museum für das Gedächtnis der Stadt.", "Un musée consacré à la mémoire de la ville.", "محطة متحفية مخصصة لذاكرة المدينة."), ktb("TR-339638/kent-bellegi-muzesi-odunpazari.html"), { indoor: true, paid: true, closedDays: [1], window: [600, 1020] }),
  place("devrim", "TÜRASAŞ Devrim Arabaları Müzesi", "center", "Tepebaşı", 55, ["city", "heritage"], t("Demiryolu sanayisi ve Devrim otomobilinin hikâyesi.", "Railway industry and the story of the Devrim car.", "Eisenbahnindustrie und die Geschichte des Devrim-Autos.", "Industrie ferroviaire et histoire de la voiture Devrim.", "صناعة السكك الحديدية وقصة سيارة ديفريم."), ktb("TR-339755/turasas-devrim-arabalari-muzesi-tepebasi.html"), { indoor: true, paid: true, closedDays: [1], window: [600, 1020] }),
  place("sazova", "Sazova Bilim, Kültür ve Sanat Parkı", "sazova", "Tepebaşı", 100, ["nature", "city"], t("Gölet çevresinde park gezisi; biletli iç mekânlar ayrı planlanır.", "Park and lake walk; ticketed interiors need a separate booking.", "Parkspaziergang; kostenpflichtige Innenräume separat planen.", "Promenade dans le parc ; intérieurs payants à prévoir séparément.", "جولة في الحديقة والبحيرة؛ الزيارات الداخلية المدفوعة تُخطط منفصلة."), "https://www.eskisehir.bel.tr/sayfalar.php?sayfalar_id=57", { walking: 2, lowWalk: false, note: "pedestrian" }),
  place("kentpark", "Kentpark", "kentpark", "Tepebaşı", 70, ["nature", "city"], t("Yeşil alan ve gölet çevresinde açık hava molası.", "An outdoor break around green space and the pond.", "Pause im Grünen am Teich.", "Pause au vert autour du plan d’eau.", "استراحة في المساحات الخضراء حول البركة."), "https://www.eskisehir.bel.tr/sayfalar.php?sayfalar_id=57", { walking: 1.3, window: [480, 1080], note: "pedestrian" }),
  place("velespit", "Velespit Parkı", "river", "Odunpazarı", 35, ["nature", "city"], t("Porsuk kıyısı bisiklet aksında dinlenme noktası.", "A rest stop on the riverside cycling corridor.", "Rastplatz am Radweg entlang des Flusses.", "Halte sur l’axe cyclable au bord du fleuve.", "محطة استراحة على محور الدراجات بمحاذاة النهر."), "https://www.eskisehir.bel.tr/icerik-detay.php?cat_icerik=1&icerik_id=11442&menu_id=24", { window: [480, 1080], note: "pedestrian", walking: 0.3 }),
  place("sumer", "Sümer Parkı · Porsuk Kıyısı", "river", "Odunpazarı", 45, ["nature"], t("Nehir boyunca kısa yürüyüş ve yeşil alan.", "A short riverside walk and green space.", "Kurzer Spaziergang am Fluss im Grünen.", "Courte promenade au vert le long du fleuve.", "نزهة قصيرة ومساحات خضراء على النهر."), "https://www.eskisehir.bel.tr/icerik-detay.php?cat_icerik=1&icerik_id=12148&menu_id=24", { window: [480, 1080], note: "pedestrian", walking: 0.8 }),
  place("battal", "Seyyid Battal Gazi Külliyesi", "seyit", "Seyitgazi", 80, ["faith", "heritage"], t("Battalname geleneği ve külliyenin anıtsal mimarisi.", "Battalname traditions and monumental architecture.", "Battalname-Tradition und monumentale Architektur.", "Tradition du Battalname et architecture monumentale.", "تقاليد بطّال نامه والعمارة الأثرية للمجمع."), ktb("TR-336884/seyyid-battal-gazi-kulliyesi-ve-turbesi-seyitgazi.html"), { note: "worship", lowWalk: false, walking: 1 }),
  place("seyitcarsi", "Seyitgazi İlçe Merkezi", "seyit", "Seyitgazi", 40, ["city", "taste"], t("Külliye gezisini yerel çarşı yaşamıyla tamamlayın.", "Complete the complex visit with local market life.", "Den Besuch mit dem lokalen Marktleben verbinden.", "Compléter la visite par la vie du bourg.", "إكمال زيارة المجمع بالتعرف على حياة البلدة."), ktb("TR-149991/seyitgazi.html")),
  place("gerdek", "Gerdekkaya Mezar Anıtı", "doganli", "Seyitgazi", 50, ["heritage", "nature"], t("Doğanlı Vadisi’nde kayaya işlenen anıtsal cephe.", "A monumental rock-cut façade in Doğanlı Valley.", "Monumentale Felsfassade im Doğanlı-Tal.", "Façade monumentale taillée dans la vallée de Doğanlı.", "واجهة أثرية منحوتة في صخر وادي دوغانلي."), frig, { lowWalk: false, note: "uneven", walking: 1.2 }),
  place("hamamkaya", "Hamamkaya Frig Kaya Mezarı", "doganli", "Seyitgazi", 35, ["heritage"], t("Gerdekkaya yakınında kaya mezarı; dışarıdan gözlem.", "A rock tomb near Gerdekkaya, viewed from outside.", "Felsgrab nahe Gerdekkaya, von außen besichtigen.", "Tombe rupestre près de Gerdekkaya, vue extérieure.", "مقبرة صخرية قرب غيرديك كايا، مشاهدة خارجية."), ktb("TR-336956/hamamkaya-frig-kaya-mezari-daglik-frigya.html"), { lowWalk: false, note: "uneven", walking: 0.8 }),
  place("midas", "Yazılıkaya · Midas Anıtı", "midas", "Han", 100, ["heritage", "nature"], t("Frig yazıtları ve kayaya oyulmuş anıtsal cephe.", "Phrygian inscriptions and a monumental rock façade.", "Phrygische Inschriften und monumentale Felsfassade.", "Inscriptions phrygiennes et façade rupestre monumentale.", "نقوش فريجية وواجهة صخرية أثرية."), ktb("TR-149984/han.html"), { lowWalk: false, note: "uneven", walking: 1.5 }),
  place("midasvillage", "Yazılıkaya Köyü", "midas", "Han", 35, ["city", "nature"], t("Arkeolojik peyzajın yanında köy dokusu ve mola.", "Village scenery beside the archaeological landscape.", "Dorfstruktur neben der archäologischen Landschaft.", "Paysage villageois près du site archéologique.", "نسيج القرية بجوار المشهد الأثري."), ktb("TR-149984/han.html")),
  place("han", "Hüsrev Paşa Camii · Han", "han", "Han", 50, ["heritage", "faith"], t("Tarihî menzil yerleşiminde Osmanlı dönemi izi.", "Ottoman heritage in a historic caravan settlement.", "Osmanisches Erbe an einer historischen Karawanenstation.", "Héritage ottoman dans une ancienne étape caravanière.", "تراث عثماني في محطة تاريخية للقوافل."), ktb("TR-149984/han.html"), { note: "worship" }),
  place("ulucami", "Sivrihisar Ulu Camii", "sivri", "Sivrihisar", 65, ["heritage", "faith"], t("UNESCO seri miras alanındaki ahşap direkli cami.", "A timber-columned mosque in a UNESCO serial property.", "Holzsäulenmoschee einer seriellen UNESCO-Welterbestätte.", "Mosquée à colonnes de bois d’un bien UNESCO en série.", "مسجد بأعمدة خشبية ضمن موقع تراث عالمي متسلسل لليونسكو."), "https://whc.unesco.org/en/list/1694/", { note: "worship", indoor: true }),
  place("sivricarsi", "Sivrihisar Tarihî Çarşısı", "sivri", "Sivrihisar", 55, ["craft", "taste", "heritage"], t("Yerel lezzetler, geleneksel doku ve esnafla buluşma.", "Local flavours, historic streets and shopkeepers.", "Lokale Küche, historische Gassen und Händler.", "Saveurs locales, rues anciennes et commerçants.", "نكهات محلية وشوارع تاريخية وتجار البلدة."), sivri),
  place("saat", "Sivrihisar Saat Kulesi", "sivri", "Sivrihisar", 40, ["heritage", "nature"], t("İlçeye bakan kaya üzerindeki tarihî saat kulesi.", "A historic clock tower on a rock above town.", "Historischer Uhrturm auf einem Felsen über der Stadt.", "Tour de l’horloge sur un rocher dominant la ville.", "برج ساعة تاريخي على صخرة تطل على البلدة."), sivri, { lowWalk: false, note: "uneven", walking: 1.1 }),
  place("church", "Surp Yerrortutyun Kilisesi", "sivri", "Sivrihisar", 40, ["heritage", "faith"], t("Taş işçiliği ve kentin çok katmanlı mirası; dış cephe ziyareti.", "Stonework and layered heritage; an exterior visit.", "Steinmetzkunst und vielfältiges Erbe; Außenbesichtigung.", "Travail de la pierre et héritages multiples ; visite extérieure.", "حرفة الحجر والتراث المتعدد؛ زيارة للواجهة الخارجية."), sivri, { note: "uneven", lowWalk: false }),
  place("sakarya", "Sakaryabaşı", "cifteler", "Çifteler", 90, ["nature"], t("Sakarya’nın kaynaklarında kıyıdan doğa gözlemi.", "Observe nature from the banks of the Sakarya springs.", "Naturbeobachtung am Ufer der Sakarya-Quellen.", "Observer la nature depuis les rives des sources de la Sakarya.", "مشاهدة الطبيعة من ضفاف منابع صقاريا."), ktb("TR-364152/cifteler-sakaryabasi.html"), { note: "water", walking: 1.3 }),
  place("cifteler", "Çifteler İlçe Merkezi", "cifteler", "Çifteler", 40, ["city", "taste"], t("Kaynak gezisi sonrası ilçe yaşamına ayrılan zaman.", "Time in town after visiting the springs.", "Zeit im Ort nach dem Besuch der Quellen.", "Une halte au bourg après les sources.", "وقت في البلدة بعد زيارة المنابع."), ktb("TR-149982/cifteler.html")),
  place("yunus", "Yunus Emre Külliyesi ve Türbesi", "yunus", "Mihalıççık", 70, ["faith", "heritage"], t("Yunus Emre’nin düşünce dünyasına ayrılan durak.", "A stop devoted to the thought of Yunus Emre.", "Eine Station zur Gedankenwelt von Yunus Emre.", "Une étape consacrée à la pensée de Yunus Emre.", "محطة للتعرف على عالم يونس إمره الفكري."), ktb("TR-364523/yunus-emre-kulliyesi-ve-turbesi.html"), { note: "worship" }),
  place("gurleyik", "Gürleyik · Dere Çevresi", "gurleyik", "Mihalıççık", 90, ["nature"], t("Dere çevresinde kısa yürüyüş; suya giriş plana dâhil değildir.", "A short streamside walk; swimming is not included.", "Kurzer Spaziergang am Bach; ohne Baden.", "Courte promenade au ruisseau ; sans baignade.", "نزهة قصيرة قرب الجدول؛ لا تشمل السباحة."), ktb("TR-149988/mihaliccik.html"), { lowWalk: false, note: "water", walking: 2 }),
  place("inonu", "İnönü İlçe Merkezi", "inonu", "İnönü", 50, ["heritage", "city"], t("İlçe dokusu ve çevredeki kaya peyzajı; mağara içine giriş yok.", "Townscape and surrounding rocks; no cave entry.", "Ortsbild und Felslandschaft; kein Höhleneinstieg.", "Bourg et paysage rocheux ; sans entrée en grotte.", "البلدة والمشهد الصخري المحيط؛ دون دخول الكهوف."), ktb("TR-149985/inonu.html")),
];
export const placeById = Object.fromEntries(places.map(p => [p.id, p])) as Record<string, Place>;

const veg = t("Etsiz sebze yemeği veya peynirli gözleme isteyin; içerik ve alerjenleri işletmeyle doğrulayın.", "Ask for a meat-free vegetable dish or cheese gözleme; confirm ingredients and allergens.", "Gemüsegericht ohne Fleisch oder Käse-Gözleme anfragen; Zutaten und Allergene prüfen.", "Demander un plat de légumes sans viande ou un gözleme au fromage ; vérifier les allergènes.", "اطلبوا طبق خضار بلا لحم أو غوزلمة بالجبن؛ تحققوا من المكونات ومسببات الحساسية.");
function food(zone: Zone, name: string, local: Localized, source = cuisine): FoodArea { return { zone, name, local, vegetarian: veg, source }; }
export const foodAreas: FoodArea[] = [
  food("center", "Taşbaşı · Adalar", t("Çibörek veya balaban; ardından met helvası için yerel esnafa uğrayın.", "Try çibörek or balaban, then visit a local shop for met halva.", "Çibörek oder Balaban probieren, danach Met-Helva beim lokalen Händler.", "Goûter le çibörek ou le balaban, puis la halva met chez un commerçant.", "جرّبوا تشيبوريك أو بالابان ثم حلوى مِت من متجر محلي.")),
  food("oldtown", "Odunpazarı Çarşı Çevresi", t("Çibörek ve ayran molası. Geleneksel çibörek kıyma içerir.", "A çibörek and ayran break. Traditional çibörek contains minced meat.", "Çibörek und Ayran. Traditionelles Çibörek enthält Hackfleisch.", "Pause çibörek et ayran. La recette traditionnelle contient de la viande hachée.", "استراحة تشيبوريك وعيران؛ الوصفة التقليدية تحتوي على لحم مفروم.")),
  food("sivri", "Sivrihisar Çarşı Çevresi", t("Dövme sucuk ve muska baklavasını sorun; ürün bulunurluğu günlük değişir.", "Ask for dövme sucuk and muska baklava; availability varies.", "Nach Dövme-Sucuk und Muska-Baklava fragen; Verfügbarkeit variiert.", "Demander le dövme sucuk et le muska baklava ; disponibilité variable.", "اسألوا عن السجق المدقوق وبقلاوة موسكا؛ التوفر متغير."), "https://goturkiye.com/eskisehir/taste"),
  food("seyit", "Seyitgazi Merkez", t("İlçe merkezinde esnaf lokantası molası; günlük menüyü yerinde seçin.", "A local restaurant break in town; choose from the daily menu.", "Pause in einer örtlichen Gaststätte; Tagesmenü vor Ort wählen.", "Pause dans un restaurant du bourg ; choisir le menu du jour.", "استراحة في مطعم محلي وسط البلدة؛ اختيار قائمة اليوم في المكان.")),
  food("cifteler", "Çifteler · Sakaryabaşı Çevresi", t("Kaynak gezisinin ardından yemek molası; güncel işletmeleri haritada inceleyin.", "A meal after the springs; check current restaurants on the map.", "Essen nach den Quellen; aktuelle Lokale auf der Karte prüfen.", "Repas après les sources ; consulter les restaurants sur la carte.", "وجبة بعد المنابع؛ اطلعوا على المطاعم الحالية في الخريطة.")),
  food("han", "Han Merkez", t("Han merkezinde günlük yemek seçeneklerini kontrol edin. Kırsalda su ve atıştırmalık taşıyın.", "Check daily meal options in Han. Carry water and snacks in the countryside.", "Tagesangebote in Han prüfen. Auf dem Land Wasser und Snacks mitnehmen.", "Vérifier les repas disponibles à Han. Emporter eau et encas en campagne.", "تحققوا من وجبات اليوم في هان واحملوا الماء والوجبات الخفيفة في الريف.")),
  food("inonu", "İnönü Merkez", t("İlçe merkezinde yerel lokanta molası; menüyü ve açık durumu kontrol edin.", "A local restaurant stop; check the menu and opening status.", "Lokale Gaststätte; Menü und Öffnung prüfen.", "Halte dans un restaurant local ; vérifier menu et ouverture.", "محطة في مطعم محلي؛ تحققوا من القائمة وحالة العمل.")),
  food("river", "Sümer · Porsuk Çevresi", t("Bisiklet molasını çevredeki yemek seçenekleriyle birleştirin; suyunuzu tamamlayın.", "Combine a cycling break with nearby food options and refill water.", "Radpause mit Essen in der Nähe verbinden und Wasser auffüllen.", "Associer pause vélo, repas à proximité et ravitaillement en eau.", "اجمعوا استراحة الدراجات مع الطعام القريب وتجديد الماء.")),
  food("sazova", "Sazova Park Çevresi", t("Park çevresinde yemek molası; biletli tesis hizmetlerini ayrıca kontrol edin.", "A meal around the park; check services at ticketed venues separately.", "Essen am Park; Angebote kostenpflichtiger Einrichtungen separat prüfen.", "Repas près du parc ; vérifier les services des espaces payants.", "وجبة قرب الحديقة؛ تحققوا منفصلاً من خدمات المرافق المدفوعة.")),
  food("kentpark", "Kentpark Çevresi", t("Park gezisinin ortasında çevredeki yemek seçeneklerini değerlendirin.", "Explore nearby meal options during your park visit.", "Während des Parkbesuchs Essensangebote in der Nähe prüfen.", "Explorer les repas à proximité pendant la visite du parc.", "اطلعوا على خيارات الطعام القريبة أثناء زيارة الحديقة.")),
];

function theme(id: string, name: Localized, stops: string[], interests: Interest[]): RouteTheme { return { id, name, stops, interests }; }
export const themes: RouteTheme[] = [
  theme("first", t("Eskişehir’e ilk bakış", "First time in Eskişehir", "Eskişehir zum ersten Mal", "Première visite à Eskişehir", "الزيارة الأولى لإسكي شهير"), ["porsuk", "odunpazari", "atlihan", "tasbasi"], ["city", "heritage"]),
  theme("phrygia", t("Frigya’nın izinde", "Following Phrygia", "Auf den Spuren Phrygiens", "Sur les traces de la Phrygie", "على خطى فريجيا"), ["midas", "gerdek", "hamamkaya", "midasvillage"], ["heritage", "nature"]),
  theme("unesco", t("Ahşabın mirası", "Heritage in timber", "Erbe aus Holz", "L’héritage du bois", "تراث الخشب"), ["ulucami", "sivricarsi", "church", "saat"], ["heritage", "faith"]),
  theme("pedal", t("Porsuk’ta pedal", "Pedal along the Porsuk", "Radeln am Porsuk", "Pédaler le long du Porsuk", "دراجات على ضفاف بورسوك"), ["velespit", "sumer", "porsuk", "sazova"], ["nature", "city"]),
  theme("flavours", t("Çarşıdan sofraya", "From market to table", "Vom Markt auf den Tisch", "Du marché à la table", "من السوق إلى المائدة"), ["tasbasi", "atlihan", "haller", "sivricarsi"], ["taste", "craft"]),
  theme("family", t("Ailece keşif", "Explore as a family", "Mit der Familie entdecken", "Découvrir en famille", "استكشاف عائلي"), ["sazova", "kentpark", "devrim", "balmumu"], ["city", "nature"]),
  theme("museum", t("Müzeler arasında", "Between museums", "Zwischen Museen", "D’un musée à l’autre", "بين المتاحف"), ["eti", "cam", "balmumu", "kentbellegi"], ["heritage", "craft"]),
  theme("faith", t("Anadolu’nun irfanı", "Anatolian wisdom", "Anatolische Weisheit", "Sagesse anatolienne", "حكمة الأناضول"), ["battal", "yunus", "ulucami", "kursunlu"], ["faith", "heritage"]),
  theme("spring", t("Sakarya’nın doğduğu yer", "Where the Sakarya begins", "Wo die Sakarya entspringt", "Aux sources de la Sakarya", "حيث تبدأ صقاريا"), ["sakarya", "cifteler"], ["nature", "taste"]),
  theme("craft", t("Ustaların Eskişehir’i", "Eskişehir’s makers", "Eskişehirs Handwerker", "Les artisans d’Eskişehir", "حرفيو إسكي شهير"), ["atlihan", "cam", "tasbasi", "kursunlu"], ["craft", "heritage"]),
  theme("rail", t("Raylardan kente", "From railways to the city", "Von der Bahn zur Stadt", "Du rail à la ville", "من السكك إلى المدينة"), ["devrim", "haller", "doktorlar", "porsuk"], ["city", "heritage"]),
  theme("river", t("Nehirle yavaşla", "Slow down by the river", "Am Fluss entschleunigen", "Ralentir au bord de l’eau", "تمهّلوا قرب النهر"), ["porsuk", "sumer", "velespit", "kentpark"], ["nature"]),
  theme("sivritaste", t("Sivrihisar’da bir sofra", "A table in Sivrihisar", "Zu Tisch in Sivrihisar", "À table à Sivrihisar", "مائدة في سيفري حصار"), ["sivricarsi", "ulucami", "saat"], ["taste", "heritage"]),
  theme("midasday", t("Yazılıkaya’da yavaş gün", "A slow day at Yazılıkaya", "Ein ruhiger Tag in Yazılıkaya", "Une journée douce à Yazılıkaya", "يوم هادئ في يازيلي كايا"), ["midas", "midasvillage"], ["heritage", "nature"]),
  theme("battalday", t("Battal Gazi ve ilçe yaşamı", "Battal Gazi and town life", "Battal Gazi und Ortsleben", "Battal Gazi et vie du bourg", "بطّال غازي وحياة البلدة"), ["battal", "seyitcarsi"], ["faith", "taste"]),
  theme("hanroad", t("Tarihî menzil yolu", "The caravan road", "Die Karawanenstraße", "La route caravanière", "طريق القوافل"), ["battal", "han", "midasvillage"], ["faith", "heritage"]),
  theme("rock", t("Kayaya işlenen hikâyeler", "Stories carved in stone", "In Stein erzählte Geschichten", "Histoires gravées dans la pierre", "قصص منقوشة في الصخر"), ["gerdek", "hamamkaya", "midas"], ["heritage"]),
  theme("yunusday", t("Yunus Emre’ye yolculuk", "A journey to Yunus Emre", "Reise zu Yunus Emre", "Voyage vers Yunus Emre", "رحلة إلى يونس إمره"), ["yunus", "ulucami", "sivricarsi"], ["faith"]),
  theme("gorge", t("Gürleyik’te doğa", "Nature at Gürleyik", "Natur in Gürleyik", "Nature à Gürleyik", "الطبيعة في غورلييك"), ["gurleyik"], ["nature"]),
  theme("inonu", t("Batıya kısa kaçamak", "A short escape west", "Kurzer Ausflug nach Westen", "Une escapade à l’ouest", "رحلة قصيرة غرباً"), ["inonu", "devrim", "haller"], ["heritage", "city"]),
  theme("glass", t("Cam, taş ve hafıza", "Glass, stone and memory", "Glas, Stein und Erinnerung", "Verre, pierre et mémoire", "الزجاج والحجر والذاكرة"), ["cam", "atlihan", "kentbellegi"], ["craft", "city"]),
  theme("ottoman", t("Külliyeden çarşıya", "From complex to bazaar", "Vom Baukomplex zum Basar", "Du complexe au bazar", "من المجمع إلى السوق"), ["kursunlu", "odunpazari", "atlihan"], ["heritage", "faith"]),
  theme("green", t("Kentte yeşil nefes", "Green city escape", "Grüne Stadtpause", "Respiration verte en ville", "فسحة خضراء في المدينة"), ["sazova", "sumer", "kentpark"], ["nature"]),
  theme("portraits", t("Kentin portreleri", "Portraits of a city", "Porträts einer Stadt", "Portraits d’une ville", "صور المدينة"), ["balmumu", "kentbellegi", "doktorlar"], ["city"]),
  theme("archaeology", t("Müzeden Frigya’ya", "From museum to Phrygia", "Vom Museum nach Phrygien", "Du musée à la Phrygie", "من المتحف إلى فريجيا"), ["eti", "midas", "gerdek"], ["heritage"]),
  theme("sivristone", t("Sivrihisar’ın taş hafızası", "Sivrihisar in stone", "Sivrihisar in Stein", "Sivrihisar en pierre", "سيفري حصار في الحجر"), ["church", "saat", "sivricarsi"], ["heritage", "craft"]),
  theme("cityhalf", t("Gardan başlayan keşif", "Discovery from the station", "Entdecken ab Bahnhof", "Découvrir depuis la gare", "اكتشاف يبدأ من المحطة"), ["devrim", "porsuk", "doktorlar"], ["city"]),
  theme("marketwalk", t("Esnafla tanış", "Meet local shopkeepers", "Lokale Händler kennenlernen", "Rencontrer les commerçants", "تعرّفوا على التجار المحليين"), ["tasbasi", "hamamyolu", "atlihan"], ["taste", "craft"]),
  theme("waterday", t("Sudan kente", "From springs to city", "Von Quellen zur Stadt", "Des sources à la ville", "من المنابع إلى المدينة"), ["sakarya", "cifteler", "porsuk"], ["nature", "city"]),
  theme("twobazaars", t("İki çarşı, iki hikâye", "Two bazaars, two stories", "Zwei Basare, zwei Geschichten", "Deux marchés, deux histoires", "سوقان وقصتان"), ["atlihan", "sivricarsi", "ulucami"], ["craft", "taste"]),
  theme("gentle", t("Kısa yürüyüş, çok keşif", "Short walks, rich discoveries", "Kurze Wege, viel entdecken", "Petites marches, belles découvertes", "مشي قصير واكتشافات كثيرة"), ["cam", "kentbellegi", "haller", "tasbasi"], ["city", "craft"]),
  theme("parkpedal", t("Parkları birleştiren pedal", "Cycling between parks", "Mit dem Rad zwischen Parks", "Relier les parcs à vélo", "دراجات تصل بين الحدائق"), ["velespit", "sumer", "sazova"], ["nature", "city"]),
  theme("localweekend", t("Yerel bir hafta sonu", "A local weekend", "Ein lokales Wochenende", "Un week-end local", "عطلة نهاية أسبوع محلية"), ["tasbasi", "odunpazari", "sakarya", "cifteler"], ["taste", "nature"]),
  theme("heritageweekend", t("Miras dolu hafta sonu", "A heritage weekend", "Ein Wochenende voller Kulturerbe", "Un week-end de patrimoine", "عطلة غنية بالتراث"), ["midas", "ulucami", "battal", "eti"], ["heritage", "faith"]),
  theme("discovery", t("Eskişehir’i derinlemesine", "Eskişehir in depth", "Eskişehir intensiv", "Eskişehir en profondeur", "إسكي شهير بعمق"), ["midas", "ulucami", "sakarya", "atlihan", "devrim"], ["heritage", "nature", "city"]),
  theme("quiet", t("Sakin kent günü", "A quiet city day", "Ein ruhiger Stadttag", "Une journée urbaine tranquille", "يوم هادئ في المدينة"), ["haller", "sumer", "cam", "hamamyolu"], ["city", "nature"]),
];
export const themeById = Object.fromEntries(themes.map(item => [item.id, item])) as Record<string, RouteTheme>;
