import { giRegistry } from "./heritage-registry";
import { text as t, type Localized, type Zone } from "./types";

export type DiscoveryKind = "food" | "craft" | "produce" | "heritage";
export type HeritageStatus = "world" | "tentative" | "living" | "local";
export interface Discovery {
  id: string; name: Localized; kind: DiscoveryKind; area: string; summary: Localized; tip: Localized;
  source: string; secondSource?: string; zones: Zone[]; stopIds?: string[]; meat?: boolean;
  registration?: (typeof giRegistry)[number]; scope?: Localized; status?: HeritageStatus; year?: number;
}
const province = t("Eskişehir ili", "Eskişehir province", "Provinz Eskişehir", "Province d’Eskişehir", "محافظة إسكي شهير");
const sivriScope = t("Eskişehir ili Sivrihisar ilçesi", "Sivrihisar district, Eskişehir", "Landkreis Sivrihisar, Eskişehir", "District de Sivrihisar, Eskişehir", "مقاطعة سيفري حصار، إسكي شهير");
function product(registryId: number, id: string, kind: DiscoveryKind, area: string, zones: Zone[], summary: Localized, tip: Localized, scope: Localized, meat = false, stopIds?: string[]): Discovery {
  const r = giRegistry.find(row => row.id === registryId);
  if (!r) throw new Error(`Missing GI record ${registryId}`);
  return { id, name: t(r.name,r.name,r.name,r.name,r.name), kind, area, zones, summary, tip, scope, meat, stopIds, registration:r, source:r.source };
}
export const products: Discovery[] = [
  product(38024,"ciborek","food","center",["center","oldtown"],
    t("İnce hamur içinde kıyma ve soğan; yarım ay biçiminde kapatılıp kızartılan Eskişehir klasiği.","A classic Eskişehir pastry: thin dough filled with minced meat and onion, folded into a crescent and fried.","Ein Klassiker: dünner Teig mit Hackfleisch und Zwiebeln, halbmondförmig gefaltet und frittiert.","Une spécialité d’Eskişehir : pâte fine garnie de viande hachée et d’oignon, repliée en demi-lune puis frite.","عجينة رقيقة بحشوة اللحم المفروم والبصل، تُطوى على شكل هلال وتُقلى؛ من نكهات إسكي شهير المميزة."),
    t("Yemek molasında taze pişirilen çiböreği sorun; paket yerine yerinde tadım tercih edebilirsiniz.","Ask for freshly cooked çibörek during your meal break; try it on site.","Fragen Sie in der Essenspause nach frisch zubereiteten Çibörek zum direkten Genießen.","À la pause repas, demandez des çibörek fraîchement préparés à déguster sur place.","اسأل في استراحة الطعام عن تشيبوريك طازج، واستمتع به في مكان تحضيره."),
    t("Türkiye","Türkiye","Türkiye","Türkiye","تركيا"),true),
  product(38026,"met-helvasi","food","center",["center","oldtown"],
    t("Un, yağ ve şekerin çekilerek lifli bir yapıya dönüştüğü, çubuk biçimli yerel şekerleme.","A local stick-shaped confection made by pulling flour, oil and sugar into fine strands.","Eine lokale, stäbchenförmige Süßigkeit aus fein gezogenen Mehl-, Öl- und Zuckerfasern.","Une confiserie locale en bâtonnets, obtenue en étirant farine, huile et sucre en filaments.","حلوى محلية على هيئة أصابع، تُصنع بسحب الدقيق والزيت والسكر إلى خيوط دقيقة."),
    t("Hediyelik kutuda üretici adı, üretim tarihi ve saklama bilgisini kontrol edin.","For a gift box, check the maker, production date and storage instructions.","Bei Geschenkpackungen Hersteller, Produktionsdatum und Lagerhinweise prüfen.","Pour un coffret cadeau, vérifiez le producteur, la date et les conditions de conservation.","عند شراء علبة هدية، تحقّق من اسم المنتج وتاريخ الإنتاج وتعليمات الحفظ."),province),
  product(1482,"eskisehir-simidi","food","center",["center","oldtown"],
    t("İncir pekmeziyle sıcak pekmezlenen, susamlı ve burgu biçimli simit. Sicilinde taş fırın ve meşe odunu kullanımı tanımlanır.","A twisted sesame ring dipped in hot fig molasses; its specification describes baking in an oak-fired stone oven.","Ein gedrehter Sesamring mit heißem Feigensirup, laut Spezifikation im eichenholzbeheizten Steinofen gebacken.","Un anneau torsadé au sésame, plongé dans la mélasse de figue chaude et cuit au four de pierre au chêne.","خبز حلقي مجدول بالسمسم ودبس التين الساخن؛ يحدد سجله الخَبز في فرن حجري بحطب البلوط."),
    t("Fırında Eskişehir Simidi adını ve incir pekmezi kullanımını sorun; günlük alın.","Ask the bakery for Eskişehir Simidi and its fig-molasses preparation; buy fresh.","In der Bäckerei nach Eskişehir Simidi mit Feigensirup fragen und frisch kaufen.","Demandez à la boulangerie l’Eskişehir Simidi à la mélasse de figue ; achetez-le frais.","اسأل المخبز عن سميت إسكي شهير واستخدام دبس التين، واشتره طازجًا."),province),
  product(37890,"luletasi","craft","center",["oldtown"],
    t("Eskişehir’in beyaz, işlenebilir taşı; ustaların elinde ince oymalı süs eşyalarına dönüşür. Menşe adıyla kayıtlıdır.","Eskişehir’s white, workable meerschaum becomes finely carved objects in artisans’ hands. It has a designation of origin.","Der weiße, gut bearbeitbare Meerschaum wird zu fein geschnitzten Objekten. Er trägt eine Ursprungsbezeichnung.","La pierre blanche et tendre d’Eskişehir devient un objet finement sculpté. Elle bénéficie d’une appellation d’origine.","حجر إسكي شهير الأبيض القابل للنحت يتحول بين أيدي الحرفيين إلى قطع دقيقة؛ وهو مسجّل بتسمية منشأ."),
    t("Atlıhan çevresinde ustaya taşın kökenini, tek parça mı pres mi olduğunu ve bakımını sorun.","Around Atlıhan, ask the maker about origin, solid versus pressed stone, and care.","Rund um Atlıhan nach Herkunft, massivem oder gepresstem Stein und Pflege fragen.","Autour d’Atlıhan, demandez l’origine de la pierre, si elle est massive ou pressée, et son entretien.","قرب أتليهان، اسأل الحرفي عن المنشأ والحجر الطبيعي أو المضغوط وطريقة العناية."),province,false,["atlihan","kursunlu","odunpazari"]),
  product(1811,"sorkun-comlegi","craft","Mihalıççık",["sorkun"],
    t("Sorkun’un yerel toprakları elle biçimlenir, açıkta pişirilir. Bu yöntem çömleğe koyu iç yüzey ve kızılımsı dış renk kazandırır.","Local Sorkun clays are shaped by hand and open-fired, producing a dark interior and a reddish exterior.","Örtliche Sorkun-Tone werden von Hand geformt und offen gebrannt: innen dunkel, außen rötlich.","Les terres de Sorkun sont façonnées à la main puis cuites à l’air libre : intérieur sombre et extérieur rougeâtre.","يُشكّل طين سوركون المحلي باليد ويُحرق في الهواء الطلق، فيكتسب سطحًا داخليًا داكنًا وخارجيًا محمرًا."),
    t("Sorkun’daki üreticiye kullanım amacını, ilk kullanım bakımını ve yolculuk için koruyucu paketlemeyi sorun.","Ask a Sorkun maker about intended use, first-use care and protective travel packaging.","Beim Hersteller in Sorkun nach Verwendungszweck, erster Pflege und Transportschutz fragen.","À Sorkun, demandez l’usage prévu, les soins avant première utilisation et un emballage protecteur.","اسأل المنتج في سوركون عن الاستخدام المقصود والعناية الأولى والتغليف الواقي أثناء السفر."),
    t("Mihalıççık ilçesi Sorkun köyü","Sorkun village, Mihalıççık","Dorf Sorkun, Mihalıççık","Village de Sorkun, Mihalıççık","قرية سوركون، ميهاليتشيك")),
  product(38261,"muska-baklavasi","food","Sivrihisar",["sivri"],
    t("İncecik yufka ve ceviz, muska biçiminde katlanır. Sivrihisar’da şerbetli ya da şerbetsiz sunulabilir.","Thin pastry and walnuts are folded into triangles; Sivrihisar serves this baklava with or without syrup.","Dünner Teig und Walnüsse werden dreieckig gefaltet; die Baklava wird mit oder ohne Sirup angeboten.","De fines feuilles et des noix sont pliées en triangles ; ce baklava se déguste avec ou sans sirop.","تُطوى رقائق العجين والجوز في مثلثات، وتُقدّم بقلاوة سيفري حصار مع القطر أو بدونه."),
    t("Şerbetli veya şerbetsiz tercihinizi belirtin; hediye alırken saklama süresini sorun.","Choose with or without syrup; ask about shelf life when buying a gift.","Mit oder ohne Sirup wählen und beim Geschenkekauf nach Haltbarkeit fragen.","Précisez avec ou sans sirop et demandez la durée de conservation pour un cadeau.","حدّد رغبتك بالقطر أو بدونه واسأل عن مدة الحفظ إن اشتريتها هدية."),sivriScope),
  product(163,"dovme-sucugu","food","Sivrihisar",["sivri"],
    t("Dana eti ve yerel ustalıkla hazırlanan fermente sucuk; ayırt edici özelliği hamurun işlenişi ve kıvamıdır.","A fermented beef sausage distinguished by local preparation skills and the texture of its worked mixture.","Eine fermentierte Rinderwurst, geprägt von örtlichem Können und der besonderen Verarbeitung ihrer Masse.","Un saucisson de bœuf fermenté dont la préparation et la texture témoignent d’un savoir-faire local.","سجق بقري مخمّر يتميز بمهارة التحضير المحلية وطريقة معالجة خليط اللحم وقوامه."),
    t("Üretici ve tescil bilgisini sorun; taşıma ve soğukta saklama koşullarını öğrenin.","Ask about the maker and registration, and check transport and refrigeration requirements.","Hersteller und Registrierung erfragen sowie Transport- und Kühlbedingungen klären.","Demandez le producteur et l’enregistrement, puis les conditions de transport et de réfrigération.","اسأل عن المنتج والتسجيل وتحقّق من شروط النقل والحفظ المبرد."),sivriScope,true),
  product(1208,"hosmerim","food","Sivrihisar",["sivri"],
    t("Kaymak, un ve az tuzun kavrulmasıyla hazırlanan yerel tatlı; üzüm pekmeziyle sunumu öne çıkar.","A local dessert of toasted cream, flour and a little salt, notably served with grape molasses.","Eine Süßspeise aus geröstetem Rahm, Mehl und wenig Salz, häufig mit Traubensirup serviert.","Un dessert de crème et de farine torréfiées avec un peu de sel, notamment servi avec de la mélasse de raisin.","حلوى محلية من القشطة والدقيق المحمّص وقليل من الملح، وتشتهر بتقديمها مع دبس العنب."),
    t("Yemekten sonra taze hazırlanan porsiyonu ve pekmezli sunumu sorabilirsiniz.","Ask about a freshly prepared portion with grape molasses after your meal.","Nach dem Essen eine frisch zubereitete Portion mit Traubensirup erfragen.","Après le repas, demandez une portion fraîchement préparée à la mélasse de raisin.","بعد الوجبة، اسأل عن حصة طازجة مع دبس العنب."),sivriScope),
  product(4763,"arabasi","food","Sivrihisar",["sivri"],
    t("Pişmiş hamur dilimleriyle sunulan berrak kanatlı et suyu çorbası. Özellikle kış sofrasıyla ilişkilidir; et suyu içerir.","A clear poultry-broth soup served with cooked dough pieces, associated especially with winter tables; it contains meat stock.","Klare Geflügelbrühe mit gekochten Teigstücken, besonders ein Wintergericht; sie enthält Fleischbrühe.","Un bouillon clair de volaille servi avec des morceaux de pâte cuite, lié aux repas d’hiver ; il contient du bouillon de viande.","حساء صافٍ من مرق الدواجن يُقدّم مع قطع عجين مطهو، ويرتبط بموائد الشتاء؛ يحتوي على مرق اللحم."),
    t("Menüde her gün bulunmayabilir; servis gününü ve hazırlanma süresini önceden sorun.","It may not be served daily; check serving days and preparation time.","Nicht unbedingt täglich erhältlich; Angebotstage und Zubereitungszeit vorher erfragen.","Il peut ne pas être servi chaque jour ; renseignez-vous sur les jours et le temps de préparation.","قد لا يُقدّم يوميًا؛ اسأل مسبقًا عن أيام تقديمه ووقت التحضير."),sivriScope,true),
  product(4784,"kelem-dolmasi","food","Sivrihisar",["sivri"],
    t("Lahana yapraklarına dana kıyma ve bulgur-göce karışımı sarılır. Muska biçimiyle tanınan bu dolma etlidir.","Cabbage leaves wrap beef mince and a bulgur–cracked-wheat mixture. This triangular dolma contains meat.","Kohlblätter umhüllen Rinderhack und eine Mischung aus Bulgur und Weizenschrot. Die dreieckigen Röllchen enthalten Fleisch.","Des feuilles de chou enveloppent du bœuf haché et un mélange de boulgour et de blé concassé. Ce dolma triangulaire contient de la viande.","تُحشى أوراق الملفوف باللحم البقري المفروم ومزيج البرغل والقمح المجروش؛ وتتميز بشكل مثلث وتحتوي على اللحم."),
    t("Yerel yemek molasında günlük üretimi sorun; lahanalı olması vejetaryen olduğu anlamına gelmez.","Ask about that day’s preparation; a cabbage-based dish is not necessarily vegetarian.","Nach der Tageszubereitung fragen; ein Kohlgericht ist nicht automatisch vegetarisch.","Demandez la préparation du jour ; un plat au chou n’est pas forcément végétarien.","اسأل عن تحضير اليوم؛ وجود الملفوف لا يعني أن الطبق نباتي."),sivriScope,true),
  product(1483,"cebe","craft","Sivrihisar",["sivri"],
    t("İnce altın veya gümüş tellerin dokunduğu bilezik. Üst yüzeyindeki balıksırtı görünüm, ustalığın izini taşır.","A bracelet woven from fine gold or silver wires, with a distinctive herringbone upper surface.","Ein aus feinen Gold- oder Silberdrähten gewebtes Armband mit charakteristischer Fischgrät-Oberfläche.","Un bracelet tissé de fins fils d’or ou d’argent, reconnaissable à sa surface en chevrons.","سوار منسوج من أسلاك ذهب أو فضة رفيعة، يتميز سطحه بنمط يشبه عظم السمكة."),
    t("Kuyumcuda el işçiliğini, metal ayarını, ağırlığı ve üreticiyi belge üzerinde sorun.","Ask the jeweller to document the maker, handwork, metal fineness and weight.","Beim Juwelier Hersteller, Handarbeit, Feingehalt und Gewicht schriftlich bestätigen lassen.","Demandez au bijoutier de documenter l’artisan, le travail manuel, le titre et le poids du métal.","اطلب من الصائغ توثيق الحرفي والعمل اليدوي وعيار المعدن ووزنه."),sivriScope),
  product(442,"incili-kupe","craft","Sivrihisar",["sivri"],
    t("İncileri, renkli taşları ve altın ya da gümüş parçaları çiçek formunda birleştiren geleneksel el işi küpe.","Traditional handmade earrings combining pearls, coloured stones and gold or silver elements in a floral form.","Traditionelle handgefertigte Ohrringe, die Perlen, farbige Steine und Gold oder Silber zur Blütenform verbinden.","Des boucles artisanales traditionnelles assemblant perles, pierres colorées et éléments d’or ou d’argent en forme florale.","أقراط يدوية تقليدية تجمع اللؤلؤ والأحجار الملونة وقطع الذهب أو الفضة في هيئة زهرة."),
    t("Ustasını ve metal ayarını öğrenin; bakım, onarım ve ürün belgesini sorun.","Ask who made it, its metal fineness, care, repairs and product documentation.","Nach Hersteller, Feingehalt, Pflege, Reparatur und Produktbeleg fragen.","Renseignez-vous sur l’artisan, le titre du métal, l’entretien, les réparations et le justificatif.","اسأل عن الحرفي وعيار المعدن والعناية والإصلاح ووثيقة المنتج."),sivriScope),
  product(4802,"sivrihisar-kilimi","craft","Sivrihisar",["sivri"],
    t("Doğal boyalı yün iplikler ahşap tezgâhta dokunur. Kilim, zilli ve cicim teknikleri yerel motifleri yaşatır.","Naturally dyed wool is woven on wooden looms; kilim, zilli and cicim techniques keep local motifs alive.","Naturgefärbte Wolle wird auf Holzwebstühlen verarbeitet; Kilim-, Zilli- und Cicim-Techniken bewahren lokale Motive.","La laine teinte naturellement est tissée sur métier en bois ; les techniques kilim, zilli et cicim perpétuent les motifs locaux.","يُنسج الصوف المصبوغ طبيعيًا على أنوال خشبية، وتحافظ تقنيات الكليم وزيلي وجيجيم على الزخارف المحلية."),
    t("Dokuyucuyu, ipliğin ve boyanın niteliğini sorun; motifin hikâyesini ustasından dinleyin.","Ask about the weaver, yarn and dyes, and hear the motif’s story from its maker.","Nach Weber, Garn und Farben fragen und sich die Geschichte des Motivs erzählen lassen.","Demandez le nom du tisserand, les fils et les teintures, puis l’histoire du motif.","اسأل عن الناسج والخيوط والأصباغ واستمع إلى حكاية الزخرفة من صانعها."),sivriScope),
  product(4823,"sarka","craft","Sivrihisar",["sivri"],
    t("Sim, sırma, boncuk ve pulla işlenen, kısa boylu geleneksel cepken. Sivrihisar’ın giyim kültürünü ve nakış ustalığını taşır.","A short traditional jacket embroidered with metallic thread, beads and sequins, expressing Sivrihisar’s dress and needlework heritage.","Eine kurze traditionelle Jacke mit Metallfäden, Perlen und Pailletten: Sivrihisars Kleidungs- und Stickkultur.","Une veste traditionnelle courte brodée de fils métalliques, perles et paillettes, témoin du costume de Sivrihisar.","سترة تقليدية قصيرة مطرّزة بخيوط معدنية وخرز وترتر، تحمل تراث لباس سيفري حصار ومهارة التطريز."),
    t("El işçiliğini ve sipariş süresini sorun; bir örneği görmek için atölyeyle önceden görüşün.","Ask about handwork and lead times; contact the workshop before visiting to see a sample.","Handarbeit und Lieferzeit erfragen; einen Musterbesuch vorher mit der Werkstatt vereinbaren.","Demandez le travail manuel et le délai ; contactez l’atelier pour voir un modèle.","اسأل عن العمل اليدوي ومدة الطلب وتواصل مع الورشة مسبقًا لمشاهدة نموذج."),sivriScope),
  product(12085,"kizilinler-bal-kabagi","produce","center",["center"],
    t("Kızılinler adıyla tanınan, beyaz-gri kabuklu ve sarı-turuncu etli bal kabağı. Tescil sınırı Tepebaşı ve Odunpazarı ilçeleridir.","A white-grey pumpkin with yellow-orange flesh, known as Kızılinler; its registered scope covers Tepebaşı and Odunpazarı.","Ein weißgrauer Kürbis mit gelb-orangem Fruchtfleisch; sein eingetragenes Herkunftsgebiet umfasst Tepebaşı und Odunpazarı.","Une courge blanc-gris à chair jaune-orange, appelée Kızılinler ; son périmètre enregistré couvre Tepebaşı et Odunpazarı.","قرع أبيض رمادي بقلب أصفر برتقالي يُعرف باسم كيزيلينلر؛ يشمل نطاق تسجيله تيبيباشي وأودونبازاري."),
    t("Mevsiminde çarşıda üretici ve köken bilgisiyle arayın. Yolculuk için uygun boyu ve saklamayı sorun.","Look for the maker and origin at the market in season; ask about travel-friendly sizes and storage.","Saisonal auf dem Markt mit Herkunftsnachweis suchen; passende Größe und Lagerung erfragen.","En saison, recherchez-le au marché avec son origine ; demandez un format adapté au voyage et sa conservation.","ابحث عنه في موسمه بالسوق مع معلومات المنتج والمنشأ، واسأل عن حجم مناسب للسفر والحفظ."),
    t("Tepebaşı ve Odunpazarı ilçeleri","Tepebaşı and Odunpazarı districts","Landkreise Tepebaşı und Odunpazarı","Districts de Tepebaşı et Odunpazarı","مقاطعتا تيبيباشي وأودونبازاري"),false,["tasbasi"]),
];

export const heritage: Discovery[] = [
  { id:"sivrihisar-ulu-camii",kind:"heritage",area:"Sivrihisar",zones:["sivri"],stopIds:["ulucami"],status:"world",year:2023,
    name:t("Sivrihisar Ulu Camii","Sivrihisar Grand Mosque","Große Moschee von Sivrihisar","Grande Mosquée de Sivrihisar","جامع سيفري حصار الكبير"),
    summary:t("Ortaçağ Anadolu’sunun Ahşap Direkli Camileri adlı seri Dünya Mirası alanının Eskişehir bileşeni. Ahşap taşıyıcılar ve oyma işçiliği öne çıkar.","Eskişehir’s component of the serial World Heritage property Wooden Hypostyle Mosques of Medieval Anatolia, distinguished by its wooden supports and carving.","Eskişehirs Teil der seriellen Welterbestätte mittelalterlicher Holzsäulenmoscheen Anatoliens, geprägt von Holzstützen und Schnitzkunst.","La composante d’Eskişehir du bien en série des mosquées hypostyles en bois de l’Anatolie médiévale, remarquable pour ses supports et sculptures.","مكوّن إسكي شهير ضمن موقع جوامع الأناضول ذات الأعمدة الخشبية المدرج في التراث العالمي؛ يتميز بأعمدته والنحت الخشبي."),
    tip:t("Sütunların ritmini ve ahşap ayrıntıları izleyin. Ziyareti ibadet saatlerine göre düzenleyin; ahşap yüzeylere dokunmayın.","Notice the rhythm of the columns and timber details. Respect prayer times and avoid touching the woodwork.","Achten Sie auf Säulenrhythmus und Holzdetails. Gebetszeiten respektieren und Holzarbeiten nicht berühren.","Observez le rythme des colonnes et les détails. Respectez les prières et ne touchez pas les boiseries.","تأمل إيقاع الأعمدة وتفاصيل الخشب، وراعِ أوقات الصلاة وتجنّب لمس الزخارف."),
    source:"https://whc.unesco.org/en/list/1694/",secondSource:"https://whc.unesco.org/en/list/1694/maps/" },
  { id:"daglik-frigya",kind:"heritage",area:"Han · Seyitgazi",zones:["midas","doganli","kumbet"],stopIds:["midas","midasvillage","gerdek","hamamkaya","kumbet"],status:"tentative",year:2015,
    name:t("Dağlık Frigya · Yazılıkaya","Mountainous Phrygia · Yazılıkaya","Bergiges Phrygien · Yazılıkaya","Phrygie montagneuse · Yazılıkaya","فريجيا الجبلية · يازيليكايا"),
    summary:t("Tüf kayalıklarına işlenen anıtlar ve kutsal peyzaj. Han’daki Midas/Yazılıkaya, Eskişehir kesiminin en güçlü simgelerindendir; bölge Geçici Liste’dedir.","Monuments carved into tuff form a sacred landscape. Han’s Midas/Yazılıkaya is a landmark of the Eskişehir section; the region is tentatively listed.","In Tuff gehauene Monumente bilden eine sakrale Landschaft. Midas/Yazılıkaya in Han prägt Eskişehirs Abschnitt; die Region steht auf der Tentativliste.","Des monuments taillés dans le tuf composent un paysage sacré. Midas/Yazılıkaya à Han marque le secteur d’Eskişehir ; la région figure sur la liste indicative.","آثار منحوتة في الصخور البركانية تشكّل مشهدًا مقدسًا. ميداس/يازيليكايا في خان من أبرز معالم قسم إسكي شهير؛ والمنطقة على القائمة التمهيدية."),
    tip:t("Kaya cephelerindeki geometrik bezemeleri uzaktan inceleyin; oyuklara tırmanmadan işaretli ziyaret alanında kalın.","Observe geometric rock façades from a distance; stay in marked visitor areas without climbing into carvings.","Geometrische Felsfassaden aus Abstand betrachten; markierte Bereiche nutzen und nicht auf Reliefs klettern.","Observez les façades géométriques à distance ; restez dans les zones balisées sans escalader les sculptures.","تأمل الواجهات الهندسية من مسافة، والتزم بمناطق الزيارة المحددة دون تسلّق المنحوتات."),
    source:"https://whc.unesco.org/en/tentativelists/6040/",secondSource:"https://www.turkishmuseums.com/museum/detail/2044-eskisehir-midas-yazilikaya-archaeological-site/2044/4" },
  { id:"odunpazari-tarihi-alan",kind:"heritage",area:"center",zones:["oldtown"],stopIds:["odunpazari","kursunlu"],status:"tentative",year:2012,
    name:t("Odunpazarı Tarihî Kentsel Alanı","Odunpazarı Historical Urban Site","Historisches Stadtgebiet Odunpazarı","Site urbain historique d’Odunpazarı","المنطقة الحضرية التاريخية في أودونبازاري"),
    summary:t("Kurşunlu Külliyesi çevresinde şekillenen sokaklar ve geleneksel konutlar, mahallenin mimari ve toplumsal hafızasını birlikte taşır.","Streets and traditional homes shaped around the Kurşunlu complex preserve the neighbourhood’s architectural and social memory.","Straßen und traditionelle Häuser rund um den Kurşunlu-Komplex bewahren das architektonische und soziale Gedächtnis des Viertels.","Les rues et maisons traditionnelles autour du complexe de Kurşunlu conservent la mémoire architecturale et sociale du quartier.","تحفظ الشوارع والمنازل التقليدية حول مجمع كورشونلو ذاكرة الحي المعمارية والاجتماعية."),
    tip:t("Cumbalara, sokağın eğimine ve avlu ilişkisine bakın; yaşayan evlerin mahremiyetini gözetin.","Look at projecting windows, sloping streets and courtyards; respect residents’ privacy.","Erker, Straßenneigung und Höfe beachten; die Privatsphäre der Bewohner respektieren.","Observez encorbellements, pentes et cours ; respectez la vie privée des habitants.","تأمل النوافذ البارزة وانحدار الشوارع والأفنية مع احترام خصوصية السكان."),
    source:"https://whc.unesco.org/en/tentativelists/5733/" },
  { id:"nasreddin-hoca-anlatilari",kind:"heritage",area:"Sivrihisar",zones:["sivri"],stopIds:["saat"],status:"living",year:2022,
    name:t("Nasreddin Hoca anlatı geleneği","Nasreddin Hodja storytelling tradition","Nasreddin-Hodscha-Erzähltradition","Tradition des récits de Nasreddin Hodja","تقليد حكايات نصر الدين خوجة"),
    summary:t("Sivrihisar’ın Hortu bağıyla hatırlanan Hoca’nın mizahı, ülkeler arasında paylaşılan anlatı geleneğidir. UNESCO kaydı bu geleneği kapsar.","Remembered locally through Sivrihisar’s Hortu connection, Hodja’s humour belongs to a storytelling tradition shared across countries. UNESCO recognises that tradition.","Durch Sivrihisars Verbindung mit Hortu ist Hodscha hier präsent. Sein Humor gehört zu einer länderübergreifenden, von der UNESCO anerkannten Erzähltradition.","Lié localement à Hortu, à Sivrihisar, l’humour de Hodja appartient à une tradition narrative partagée entre pays et reconnue par l’UNESCO.","ترتبط ذاكرة خوجة محليًا بهورتو في سيفري حصار؛ وفكاهته جزء من تقليد حكائي مشترك بين دول تعترف به اليونسكو."),
    tip:t("İlçeyi gezerken bir anlatıyı yerel rehberden dinleyin; kaydın bir yapı veya tüm ilçe tescili olmadığını hatırlayın.","Ask a local guide for an anecdote; the listing does not designate a building or the whole district.","Einen lokalen Guide um eine Geschichte bitten; der Eintrag gilt keinem Gebäude oder ganzen Landkreis.","Demandez une anecdote à un guide local ; l’inscription ne désigne ni un bâtiment ni tout le district.","اطلب من مرشد محلي حكاية؛ فالتسجيل لا يخص مبنى أو المقاطعة بأكملها."),
    source:"https://ich.unesco.org/en/RL/telling-tradition-of-nasreddin-hodja-molla-nesreddin-molla-ependi-apendi-afendi-kozhanasyr-anecdotes-01705",secondSource:"https://eskisehir.ktb.gov.tr/TR-336932/nasreddin-hoca39nin-evi-sivrihisar.html" },
  { id:"battal-gazi-kulliyesi",kind:"heritage",area:"Seyitgazi",zones:["seyit"],stopIds:["battal"],status:"local",
    name:t("Seyyid Battal Gazi Külliyesi","Seyyid Battal Gazi Complex","Seyyid-Battal-Gazi-Komplex","Complexe de Seyyid Battal Gazi","مجمع سيد بطّال غازي"),
    summary:t("Seyitgazi’nin inanç ve mimarlık hafızası. Farklı dönemlerde genişleyen külliye, eğitim ve derviş gelenekleriyle de ilişkilidir.","A place of faith and architectural memory in Seyitgazi, expanded across periods and linked with learning and dervish traditions.","Ein Ort religiösen und architektonischen Gedächtnisses, über verschiedene Epochen erweitert und mit Bildung und Derwischtraditionen verbunden.","Un lieu de mémoire religieuse et architecturale, agrandi au fil des époques et lié à l’enseignement et aux traditions derviches.","معلم للذاكرة الدينية والمعمارية في سيتغازي، توسّع عبر العصور وارتبط بالتعليم وتقاليد الدراويش."),
    tip:t("Avlu, türbe ve ortak kullanım mekânları arasındaki ilişkiyi izleyin; ziyaret ve ibadet düzenine uyun.","Observe the relationship between courtyard, tomb and communal spaces; follow visiting and worship arrangements.","Das Zusammenspiel von Hof, Grab und Gemeinschaftsräumen betrachten; Besuchs- und Gebetsregeln beachten.","Observez le lien entre cour, tombeau et espaces communs ; respectez les modalités de visite et de culte.","تأمل العلاقة بين الفناء والضريح والمساحات المشتركة، واتبع نظام الزيارة والعبادة."),
    source:"https://eskisehir.ktb.gov.tr/TR-336884/seyyid-battal-gazi-kulliyesi-ve-turbesi-seyitgazi.html" },
  { id:"pessinus-antik-kenti",kind:"heritage",area:"Sivrihisar",zones:["pessinus"],stopIds:["pessinus"],status:"local",
    name:t("Pessinus · Ballıhisar","Pessinus · Ballıhisar","Pessinus · Ballıhisar","Pessinonte · Ballıhisar","بيسينوس · باللي حصار"),
    summary:t("Ballıhisar’daki antik yerleşme, Ana Tanrıça/Kybele kültünün önemli merkezlerinden biridir. Köy yaşamı ile arkeolojik katmanlar yan yanadır.","The ancient settlement at Ballıhisar was an important centre of the Mother Goddess/Cybele cult. Village life and archaeological layers sit side by side.","Die antike Siedlung in Ballıhisar war ein wichtiges Zentrum des Muttergöttin-/Kybele-Kults. Dorfleben und archäologische Schichten liegen nebeneinander.","L’établissement antique de Ballıhisar était un centre important du culte de la Déesse Mère/Cybèle. Village et vestiges se côtoient.","كانت المستوطنة القديمة في باللي حصار مركزًا مهمًا لعبادة الإلهة الأم/كوبيلي، وتتجاور فيها حياة القرية والطبقات الأثرية."),
    tip:t("Kalıntıları yerleşim bütünü içinde okuyun; taş veya seramik parçası toplamadan belirlenmiş alanda gezin.","Read the remains as part of a settlement; stay in designated areas and leave stones and pottery in place.","Die Reste als Siedlung betrachten; vorgesehene Wege nutzen und Steine und Keramik liegen lassen.","Lisez les vestiges comme un ensemble habité ; suivez les zones autorisées et laissez pierres et tessons sur place.","تأمل البقايا ضمن النسيج السكني والتزم بمناطق الزيارة، واترك الأحجار والفخار في مكانهما."),
    source:"https://eskisehir.ktb.gov.tr/TR-336891/pessinus-ballihisar-antik-kenti-sivrihisar.html" },
];
export const discoveries = [...products, ...heritage];
