import { text as t, type Locale, type TransitRide } from "./types";
const strings = {
  earliest: t("En erken çıkış", "Earliest departure", "Frühester Start", "Départ au plus tôt", "أقرب وقت للانطلاق"),
  early: t("06:00–19:00 arasında uygun seferi bul", "Try 06:00–19:00", "06:00–19:00 versuchen", "Essayer 06:00–19:00", "تجربة 06:00–19:00"),
  title: t("Toplu taşıma ile keşfet", "Explore by public transport", "Mit Bus und Tram entdecken", "Découvrir en transports", "الاكتشاف بالنقل العام"),
  intro: t("Geziye seçtiğiniz noktadan başlayın. Hatlar, aktarmalar, yürüyüş ve dönüş seferi programın süresine dâhildir. Erken çıkış seçilirse uygun sefer için başlangıç saati ileri alınabilir.", "Start at your selected point. Lines, transfers, walking and return services count towards your day. An early starting window may be shifted later to suit departures.", "Start am gewählten Ort. Linien, Umstiege, Fußwege und Rückfahrt sind im Tagesplan enthalten. Bei frühem Zeitfenster kann der Start für passende Fahrten später liegen.", "Départ de votre point choisi. Lignes, correspondances, marche et retour sont intégrés au programme. Un départ matinal peut être décalé pour correspondre au service.", "ابدؤوا من نقطتكم المختارة. يشمل اليوم الخطوط والتبديل والمشي وخدمة العودة. يمكن تأخير البداية المبكرة لتناسب موعد الخدمة."),
  needDate: t("Sefer gününü hesaplamak için gezi tarihi seçin.", "Choose a travel date to check the service day.", "Reisedatum wählen, um den Verkehrstag zu prüfen.", "Choisissez une date pour vérifier les services.", "اختاروا تاريخ الرحلة للتحقق من أيام الخدمة."),
  holiday: t("Resmî tatil tarifesini kullan", "Use public holiday timetable", "Feiertagsfahrplan verwenden", "Utiliser le service de jour férié", "استخدام جدول العطلات الرسمية"),
  holidayNote: t("Resmî tatil ve bayram günlerinde işaretleyin. Özel günlerdeki geçici sefer değişikliklerini ayrıca kontrol edin.", "Select for public and religious holidays. Check temporary service changes for special dates separately.", "An gesetzlichen und religiösen Feiertagen wählen. Vorübergehende Änderungen separat prüfen.", "À cocher pour les jours fériés et fêtes religieuses. Vérifiez les changements temporaires.", "فعّلوا الخيار في العطلات الرسمية والدينية وتحققوا من التغييرات المؤقتة."),
  checked: t("Veri kontrolü", "Data checked", "Daten geprüft", "Données vérifiées", "فحص البيانات"),
  updated: t("Kurumun tarife tarihi", "Operator’s timetable date", "Fahrplanstand des Betreibers", "Date du tarif de l’opérateur", "تاريخ جدول المشغّل"),
  snapshot: t("Resmî kaynaklardan alınan tarife kopyası; canlı araç takibi değildir. Otobüste terminal kalkışı yayımlanan saattir. Ara durak geçişleri, varışlar ve yürüyüşler tahminidir; tramvay beklemesi yayımlanan sefer sıklığına dayanır.", "A timetable snapshot from official sources, not live tracking. Bus terminal departures are published times. Intermediate stops, arrivals and walks are estimates; tram waiting uses published frequencies.", "Fahrplankopie aus offiziellen Quellen, keine Live-Ortung. Busabfahrten an Endstellen sind veröffentlicht. Zwischenhalte, Ankunft und Fußwege sind geschätzt; Tramwartezeiten nutzen veröffentlichte Takte.", "Copie des horaires officiels, sans suivi en direct. Départs des bus au terminus publiés ; passages, arrivées et marches estimés. L’attente du tram suit les fréquences publiées.", "نسخة من الجداول الرسمية وليست تتبعاً مباشراً. انطلاق الحافلة من المحطة النهائية منشور؛ المرور والوصول والمشي تقديري، وانتظار الترام مبني على التواتر المنشور."),
  future: t("Bu tarih veri kontrolünden uzakta. Program ön taslaktır; seyahatten önce güncel tarifeyi kontrol edin.", "This date is far from the data check. Treat this as a draft and verify the timetable before travel.", "Das Datum liegt weit vom Datenstand entfernt. Entwurf vor der Reise mit aktuellem Fahrplan prüfen.", "Cette date est éloignée de la vérification. Programme provisoire à vérifier avant le voyage.", "التاريخ بعيد عن تاريخ فحص البيانات. هذه مسودة؛ تحققوا من الجدول قبل السفر."),
  coverage: t("İlçe hatları ve sefer uygunluğu", "District lines and service availability", "Bezirkslinien und Verfügbarkeit", "Lignes des districts et disponibilité", "خطوط المناطق وتوفر الخدمة"),
  coverageNote: t("Hat bulunması aynı gün gezi ve dönüş yapılabileceği anlamına gelmez. Aşağıdaki saatler terminal kalkışlarıdır. Ara durak, gece ve koşullu seferler için resmî tarife esas alınır.", "A listed line does not guarantee a same-day visit and return. Times below are terminal departures. Check the official timetable for intermediate, night and conditional services.", "Eine Linie garantiert keine Tagestour mit Rückfahrt. Angezeigt werden Endstellenabfahrten. Zwischen-, Nacht- und Sonderfahrten offiziell prüfen.", "Une ligne ne garantit pas un aller-retour touristique dans la journée. Horaires de départ des terminus ; consultez l’opérateur pour les services particuliers.", "وجود خط لا يضمن جولة وعودة في اليوم نفسه. الأوقات أدناه من المحطات النهائية؛ راجعوا الجدول للخدمات الخاصة."),
  noMatch: t("Seçilen gün, saatler ve ilçeler için gidiş–ziyaret–dönüş birlikte sığmıyor. Aşağıdaki hat saatlerini inceleyin; başlangıcı erkene alın, dönüşü uzatın veya başka gün seçin.", "Outbound travel, visits and return do not all fit these dates, times and districts. Review the services below; start earlier, return later or choose another day.", "Hinreise, Besuch und Rückfahrt passen nicht zusammen. Fahrpläne unten prüfen; früher starten, später zurückkehren oder anderen Tag wählen.", "Aller, visites et retour ne tiennent pas dans ces horaires. Consultez les lignes ; partez plus tôt, rentrez plus tard ou changez de jour.", "لا يتسع البرنامج للذهاب والزيارة والعودة. راجعوا الخطوط؛ ابدؤوا أبكر أو عودوا لاحقاً أو اختاروا يوماً آخر."),
  noService: t("Bu gün türü için doğrulanmış sefer yok", "No verified service for this day type", "Keine bestätigte Fahrt für diesen Tag", "Aucun service vérifié pour ce type de jour", "لا توجد خدمة مؤكدة لهذا النوع من الأيام"),
  missing: t("Bu alana kadar doğrulanmış bağlantı yok; ilçe merkezine giden hat, uzak ören yerine ulaşım olarak kabul edilmez.", "No verified connection to this area; a district-centre bus does not prove access to an outlying heritage site.", "Keine bestätigte Verbindung zu diesem Gebiet. Ein Bezirksbus erschließt nicht automatisch entfernte Ausgrabungen.", "Pas de liaison vérifiée vers ce secteur ; un bus au centre du district ne dessert pas forcément les sites éloignés.", "لا توجد وصلة مؤكدة لهذه المنطقة؛ حافلة مركز المنطقة لا تثبت الوصول إلى المواقع الأثرية البعيدة."),
  weekday: t("Hafta içi", "Weekday", "Werktag", "Semaine", "أيام الأسبوع"),
  saturday: t("Cumartesi", "Saturday", "Samstag", "Samedi", "السبت"),
  sunday: t("Pazar / resmî tatil", "Sunday / public holiday", "Sonntag / Feiertag", "Dimanche / jour férié", "الأحد / عطلة رسمية"),
  line: t("Hat", "Line", "Linie", "Ligne", "الخط"), bus: t("Otobüs", "Bus", "Bus", "Bus", "حافلة"), tram: t("Tramvay", "Tram", "Tram", "Tram", "ترام"),
  board: t("Biniş", "Board", "Einstieg", "Montée", "الصعود"), alight: t("İniş", "Alight", "Ausstieg", "Descente", "النزول"),
  terminal: t("Terminal kalkışı", "Terminal departure", "Abfahrt Endstelle", "Départ du terminus", "انطلاق المحطة النهائية"),
  estimate: t("tahmini", "estimated", "geschätzt", "estimé", "تقديري"),
  frequency: t("Sefer aralığı", "Service interval", "Takt", "Fréquence", "فاصل الخدمة"),
  transfer: t("aktarma", "transfer", "Umstieg", "correspondance", "تبديل"),
  walking: t("Durağa erişim ve aktarma yürüyüşü", "Stop access and transfer walking", "Zugang und Umstiegsfußwege", "Marche d’accès et de correspondance", "المشي للمحطة والتبديل"),
  waiting: t("Bekleme ve biniş payı", "Waiting and boarding buffer", "Warte- und Einstiegspuffer", "Attente et marge d’embarquement", "الانتظار وهامش الصعود"),
  return: t("Dönüş bağlantısı programa dâhil", "Return connection included", "Rückfahrt eingeplant", "Retour inclus", "وصلة العودة ضمن البرنامج"),
  onlyWalk: t("Bu günün durakları yürüyerek bağlanıyor; otobüs veya tramvay yolculuğu gerekmiyor.", "This day’s stops are connected on foot; no bus or tram ride is needed.", "Die Tagesziele sind zu Fuß verbunden; Bus oder Tram sind nicht nötig.", "Les étapes se relient à pied ; aucun trajet en bus ou tram n’est nécessaire.", "محطات اليوم متصلة سيراً ولا تحتاج حافلة أو تراماً."),
  source: t("Resmî tarife", "Official timetable", "Offizieller Fahrplan", "Horaires officiels", "الجدول الرسمي"),
  live: t("Canlı durak ve araç bilgisi · ESTRAM Mobil", "Live stops and vehicles · ESTRAM Mobile", "Live-Haltestellen und Fahrzeuge · ESTRAM Mobil", "Arrêts et véhicules en direct · ESTRAM Mobile", "المحطات والمركبات مباشرة · ESTRAM Mobil"),
  details: t("Ulaşım ayrıntıları", "Journey details", "Verbindungsdetails", "Détails du trajet", "تفاصيل التنقل"),
};
export function transitCopy(locale: Locale) { return Object.fromEntries(Object.entries(strings).map(([key,value]) => [key,value[locale]])) as Record<keyof typeof strings,string>; }
const clock = (m: number) => `${Math.floor(m/60).toString().padStart(2,"0")}:${(m%60).toString().padStart(2,"0")}`;
export function rideText(ride: TransitRide, locale: Locale): string {
  const c=transitCopy(locale);
  return `${c[ride.vehicle]} ${ride.line} · ${ride.direction}\n${c.board}: ${ride.board} · ${ride.estimatedBoard ? "~" : ""}${clock(ride.depart)}${ride.estimatedBoard ? ` (${c.estimate})` : ""}\n${c.alight}: ${ride.alight} · ~${clock(ride.arrive)} (${c.estimate})${ride.terminalDeparture !== undefined ? `\n${c.terminal}: ${ride.terminal} · ${clock(ride.terminalDeparture)}` : `\n${c.frequency}: ${ride.headway} min`}\n${c.source}: ${ride.source}`;
}
