import { sqliteTable,text,integer,primaryKey,index } from "drizzle-orm/sqlite-core";
// Counts only. Conversations, passwords and visitor locations are never stored here.
export const aiUsage=sqliteTable("ai_usage",{key:text("key").notNull(),bucket:integer("bucket").notNull(),count:integer("count").notNull().default(0)},table=>[primaryKey({columns:[table.key,table.bucket]})]);

// Social product data is distinct from the anonymous AI usage counters above.
export const profiles=sqliteTable('social_profiles',{id:text('id').primaryKey(),handle:text('handle').notNull().unique(),name:text('name').notNull(),bio:text('bio').notNull().default(''),publicName:text('public_name').notNull().default('Gezgin'),publicBio:text('public_bio').notNull().default(''),status:text('status').notNull().default('pending'),revision:integer('revision').notNull().default(1),createdAt:text('created_at').notNull()},t=>[index('social_profiles_lookup').on(t.status,t.createdAt)]);
export const accounts=sqliteTable('social_accounts',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>profiles.id,{onDelete:'cascade'}),provider:text('provider').notNull(),subject:text('subject').notNull().unique(),passwordHash:text('password_hash'),salt:text('salt')},t=>[index('social_accounts_lookup').on(t.userId)]);
export const sessions=sqliteTable('social_sessions',{hash:text('hash').primaryKey(),userId:text('user_id').notNull().references(()=>profiles.id,{onDelete:'cascade'}),expires:integer('expires').notNull()},t=>[index('social_sessions_lookup').on(t.userId,t.expires)]);
export const oauthStates=sqliteTable('social_oauth_states',{hash:text('hash').primaryKey(),provider:text('provider').notNull(),nonce:text('nonce').notNull(),verifier:text('verifier').notNull(),appChallenge:text('app_challenge').notNull(),returnKind:text('return_kind').notNull(),expires:integer('expires').notNull()});
export const handoffs=sqliteTable('social_handoffs',{hash:text('hash').primaryKey(),userId:text('user_id').notNull().references(()=>profiles.id,{onDelete:'cascade'}),challenge:text('challenge').notNull(),expires:integer('expires').notNull()});
export const posts=sqliteTable('social_posts',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>profiles.id,{onDelete:'cascade'}),title:text('title').notNull(),body:text('body').notNull(),preferences:text('preferences').notNull(),placeIds:text('place_ids').notNull(),districts:text('districts').notNull(),mode:text('mode').notNull(),days:integer('days').notNull(),status:text('status').notNull().default('pending'),revision:integer('revision').notNull().default(1),aiState:text('ai_state').notNull().default('unavailable'),createdAt:text('created_at').notNull()},t=>[index('social_posts_lookup').on(t.status,t.createdAt)]);
export const media=sqliteTable('social_media',{id:text('id').primaryKey(),postId:text('post_id').notNull().references(()=>posts.id,{onDelete:'cascade'}),userId:text('user_id').notNull().references(()=>profiles.id,{onDelete:'cascade'}),objectKey:text('object_key').notNull().unique(),kind:text('kind').notNull(),mime:text('mime').notNull(),bytes:integer('bytes').notNull(),caption:text('caption').notNull().default(''),status:text('status').notNull().default('pending'),createdAt:text('created_at').notNull()},t=>[index('social_media_lookup').on(t.postId,t.status)]);
export const votes=sqliteTable('social_votes',{postId:text('post_id').notNull().references(()=>posts.id,{onDelete:'cascade'}),userId:text('user_id').notNull().references(()=>profiles.id,{onDelete:'cascade'}),liked:integer('liked').notNull().default(0),rating:integer('rating').notNull().default(0)},t=>[primaryKey({columns:[t.postId,t.userId]})]);
export const comments=sqliteTable('social_comments',{id:text('id').primaryKey(),postId:text('post_id').notNull().references(()=>posts.id,{onDelete:'cascade'}),userId:text('user_id').notNull().references(()=>profiles.id,{onDelete:'cascade'}),body:text('body').notNull(),status:text('status').notNull().default('pending'),revision:integer('revision').notNull().default(1),createdAt:text('created_at').notNull()},t=>[index('social_comments_lookup').on(t.postId,t.status)]);
export const reports=sqliteTable('social_reports',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>profiles.id,{onDelete:'cascade'}),targetType:text('target_type').notNull(),targetId:text('target_id').notNull(),reason:text('reason').notNull(),detail:text('detail').notNull().default(''),status:text('status').notNull().default('open'),createdAt:text('created_at').notNull()},t=>[index('social_reports_lookup').on(t.status,t.createdAt)]);
export const requests=sqliteTable('social_requests',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>profiles.id,{onDelete:'cascade'}),kind:text('kind').notNull(),district:text('district').notNull(),listingId:text('listing_id'),date:text('date').notNull(),time:text('time').notNull(),people:integer('people').notNull(),language:text('language').notNull(),note:text('note').notNull().default(''),status:text('status').notNull().default('demo'),createdAt:text('created_at').notNull()},t=>[index('social_requests_lookup').on(t.userId,t.createdAt)]);
export const visits=sqliteTable('social_visits',{userId:text('user_id').notNull().references(()=>profiles.id,{onDelete:'cascade'}),placeId:text('place_id').notNull(),date:text('date').notNull()},t=>[primaryKey({columns:[t.userId,t.placeId]})]);
export const reviewLog=sqliteTable('social_review_log',{id:text('id').primaryKey(),reviewerId:text('reviewer_id').notNull(),targetType:text('target_type').notNull(),targetId:text('target_id').notNull(),decision:text('decision').notNull(),revision:integer('revision').notNull(),createdAt:text('created_at').notNull()});
export const demoSeeds=sqliteTable('social_demo_seeds',{id:text('id').primaryKey()});
export const travelKit=sqliteTable('social_kit',{userId:text('user_id').notNull().references(()=>profiles.id,{onDelete:'cascade'}),kind:text('kind').notNull(),ref:text('ref').notNull(),createdAt:text('created_at').notNull()},t=>[primaryKey({columns:[t.userId,t.kind,t.ref]})]);
