'use client';
import {isNativeApp} from '../mobile/native';
import {registerPlugin} from '@capacitor/core';
export const COMMUNITY_ORIGIN=(process.env.NEXT_PUBLIC_COMMUNITY_API_ORIGIN??((process.env.NEXT_PUBLIC_GITHUB_PAGES==='true'||process.env.NEXT_PUBLIC_MOBILE_APP==='true')?'https://eskisehir-turizm-altyapi.ozgurarc.chatgpt.site':'')).replace(/\/$/,'');
const vault=registerPlugin<{get(o:{key:string}):Promise<{value:string|null}>;set(o:{key:string;value:string}):Promise<void>;remove(o:{key:string}):Promise<void>}>('CommunityVault');
let sessionToken='';
export const AUTH_EVENT='etahb-community-auth';
export class SocialClientError extends Error{constructor(public code:string,public status=0){super(code);}}
export async function restoreSession(){if(isNativeApp()){try{const data=JSON.parse((await vault.get({key:'session'})).value??'null');if(data?.expires>Date.now())sessionToken=data.token;else await vault.remove({key:'session'});}catch{sessionToken='';}}else{try{const data=JSON.parse(sessionStorage.getItem('etahb-community-session')??'null');if(data?.expires>Date.now())sessionToken=data.token;else sessionStorage.removeItem('etahb-community-session');}catch{sessionToken='';}}}
export async function storeSession(session:{token:string;expires:number}){sessionToken=session.token;if(isNativeApp())await vault.set({key:'session',value:JSON.stringify(session)});else sessionStorage.setItem('etahb-community-session',JSON.stringify(session));window.dispatchEvent(new Event(AUTH_EVENT));}
export async function clearSession(){sessionToken='';if(isNativeApp())await vault.remove({key:'session'});else sessionStorage.removeItem('etahb-community-session');window.dispatchEvent(new Event(AUTH_EVENT));}
export async function socialFetch(path:string,options:RequestInit={}){if(!path.startsWith('/'))throw new SocialClientError('invalid_request');const headers=new Headers(options.headers);if(sessionToken)headers.set('Authorization','Bearer '+sessionToken);let r:Response;try{r=await fetch(COMMUNITY_ORIGIN+'/api/community'+path,{...options,headers,credentials:'include',signal:options.signal??AbortSignal.timeout(25000)});}catch{throw new SocialClientError('service_unavailable');}if(!r.ok){let code='service_unavailable';try{code=(await r.json()).error??code;}catch{}throw new SocialClientError(code,r.status);}return r;}
export async function socialApi<T=any>(path:string,method='GET',body?:unknown):Promise<T>{const r=await socialFetch(path,{method,headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});return r.json();}
const random=()=>btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
async function verifierStore(value:string|null){if(isNativeApp()){if(value)await vault.set({key:'oauth',value});else await vault.remove({key:'oauth'});}else if(value)sessionStorage.setItem('etahb-oauth',value);else sessionStorage.removeItem('etahb-oauth');}
export async function beginSocialLogin(provider:'google'|'facebook'){
 const verifier=random(),challenge=btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
 await verifierStore(JSON.stringify({verifier,expires:Date.now()+600000}));const result=await socialApi<{url:string}>('/auth/start','POST',{provider,challenge,returnKind:isNativeApp()?'native':'web'});
 const url=new URL(result.url),base=new URL(COMMUNITY_ORIGIN||location.origin);if(url.origin!==base.origin||url.pathname!=='/api/community/oauth/launch')throw new SocialClientError('invalid_request');
 if(isNativeApp()){const {Browser}=await import('@capacitor/browser');await Browser.open({url:url.toString()});}else location.assign(url.toString());
}
export async function finishSocialLogin(code:string){if(!/^[A-Za-z0-9_-]{43}$/.test(code))throw new SocialClientError('invalid_request');let value:string|null;if(isNativeApp())value=(await vault.get({key:'oauth'})).value;else value=sessionStorage.getItem('etahb-oauth');const data=JSON.parse(value??'null');if(!data?.verifier||data.expires<Date.now())throw new SocialClientError('oauth_expired');const session=await socialApi<{token:string;expires:number}>('/auth/exchange','POST',{code,verifier:data.verifier});await verifierStore(null);await storeSession(session);if(isNativeApp()){const {Browser}=await import('@capacitor/browser');await Browser.close().catch(()=>{});}}
export async function preparePhoto(file:File){if(!file.type.startsWith('image/'))return file;if(file.size>8*1024*1024)throw new SocialClientError('media_too_large');const img=await createImageBitmap(file);try{if(img.width*img.height>50_000_000)throw new SocialClientError('media_too_large');const scale=Math.min(1,1920/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw new SocialClientError('unsupported_media');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new SocialClientError('unsupported_media')),'image/jpeg',.86));return new File([blob],file.name.replace(/\.[^.]*$/,'')+'.jpg',{type:'image/jpeg'});}finally{img.close();}}
