import {districtNames} from '../routing/data';
import type {District,Locale,Interest} from '../routing/types';
export interface DemoGuide {id:string;district:District;name:string;languages:Locale[];specialty:Interest;demo:true;licenseVerified:false;}
export interface DemoHome {id:string;district:District;name:string;capacity:number;rooms:number;type:'room'|'home';demo:true;permitVerified:false;}
const strengths:Record<District,Interest[]>={Alpu:['craft','nature','heritage'],Beylikova:['nature','taste','city'],Çifteler:['nature','taste','city'],Günyüzü:['heritage','nature','taste'],Han:['phrygia','heritage','nature'],İnönü:['heritage','nature','city'],Mahmudiye:['nature','heritage','taste'],Mihalgazi:['nature','taste','city'],Mihalıççık:['nature','faith','craft'],Odunpazarı:['heritage','craft','taste'],Sarıcakaya:['nature','taste','heritage'],Seyitgazi:['faith','phrygia','heritage'],Sivrihisar:['heritage','taste','craft'],Tepebaşı:['city','heritage','taste']};
const languageGroups:Locale[][]=[['tr','en'],['tr','de','fr'],['tr','ar']];
export const demoGuides:DemoGuide[]=districtNames.flatMap((district,i)=>[0,1,2].map(n=>({id:`demo-guide-${String(i*3+n+1).padStart(2,'0')}`,district,name:`${district} · ${String(n+1).padStart(2,'0')}`,languages:languageGroups[n],specialty:strengths[district][n],demo:true,licenseVerified:false})));
export const demoHomes:DemoHome[]=districtNames.flatMap((district,i)=>Array.from({length:i<12?3:2},(_,n)=>({id:`demo-home-${String((i<13?i*3:38)+n+1).padStart(2,'0')}`,district,name:`${district} · ${String(n+1).padStart(2,'0')}`,capacity:[2,4,6][n],rooms:n+1,type:n===0?'room' as const:'home' as const,demo:true as const,permitVerified:false as const})));
export function matchGuides(districts:District[],locale:Locale,interests:Interest[]=[]){return demoGuides.filter(g=>!districts.length||districts.includes(g.district)).map(g=>({...g,match:(g.languages.includes(locale)?2:0)+(interests.includes(g.specialty)?1:0)})).sort((a,b)=>b.match-a.match||a.id.localeCompare(b.id));}
export function matchHomes(districts:District[],people=1){return demoHomes.filter(h=>(!districts.length||districts.includes(h.district))&&h.capacity>=people).sort((a,b)=>a.capacity-b.capacity||a.id.localeCompare(b.id));}
