import type {Locale} from '../routing/types';
const rows=`localStart|Örnek rota ilk duraktaki bölgede başlar. Başlangıç noktasına ulaşımı ayrıca planlayın.|The sample starts in the first stop’s area. Plan your journey to that starting point separately.|Das Beispiel beginnt im Gebiet des ersten Stopps. Anreise zum Startpunkt separat planen.|L’exemple commence dans le secteur de la première étape. Prévoyez séparément l’accès au départ.|يبدأ المثال في منطقة المحطة الأولى. خطط للوصول إلى نقطة البداية بشكل منفصل.
notice|Bu alandaki 20 rota, 10 öne çıkan yer, bot yorumları, örnek beğeniler ve fotoğraf galerileri sistemin nasıl çalıştığını test etmek için eklenmiştir. Gerçek kullanıcı deneyimi veya ziyaret istatistiği değildir.|The 20 routes, 10 featured places, bot comments, sample likes and photo galleries demonstrate how the system works. They are not real user experiences or visitor statistics.|Die 20 Routen, 10 Orte, Bot-Kommentare, Beispiel-Likes und Fotogalerien zeigen die Funktionsweise. Sie sind keine echten Reiseberichte oder Besucherstatistiken.|Les 20 itinéraires, 10 lieux, commentaires de bots, mentions J’aime et galeries illustrent le fonctionnement. Il ne s’agit pas d’expériences réelles ni de statistiques de visite.|المسارات العشرون والأماكن العشرة وتعليقات البوت والإعجابات والصور أمثلة لاختبار النظام، وليست تجارب مستخدمين حقيقية أو إحصاءات زيارة.
access|Demo açık: profil oluşturmadan deneyin|Demo access: no profile needed|Demo ohne Profil ausprobieren|Démo accessible sans profil|جرّب العرض دون إنشاء ملف
private|Denemen sana özel kaydedildi. Diğer ziyaretçilere yayımlanmaz. Gerçek paylaşımlar içerik kontrolünden geçer.|Your trial is saved privately and is not published to other visitors. Real posts require content review.|Ihr Versuch wird privat gespeichert, nicht für andere veröffentlicht. Echte Beiträge werden geprüft.|Votre essai est enregistré en privé. Il n’est pas publié aux autres visiteurs. Les vrais contenus sont vérifiés.|حُفظت تجربتك بشكل خاص ولا تُنشر للزوار الآخرين. تخضع المشاركات الحقيقية لمراجعة المحتوى.
preview|Sana özel demo|Your private demo|Ihre private Demo|Votre démo privée|عرضك الخاص
bot|Demo bot|Demo bot|Demo-Bot|Bot de démo|بوت تجريبي
sample|Örnek içerik|Sample content|Beispielinhalt|Exemple|محتوى تجريبي
gallery|Kaynaklı örnek fotoğraflar; demo kullanıcının çekimi değildir.|Sourced sample photos, not photos taken by the demo user.|Belegte Beispielfotos, nicht vom Demo-Nutzer aufgenommen.|Photos d’illustration sourcées, non prises par l’utilisateur fictif.|صور نموذجية موثقة، لم يلتقطها المستخدم التجريبي.
trend|Bu 10 yer, örnek rotalardaki duraklar ve kurgusal beğenilerle gösterilir. Gerçek kullanım başladığında sıralama gerçek etkileşimlerden oluşacak.|These 10 places use sample routes and fictional likes. In live use, ranking will reflect real activity.|Diese 10 Orte beruhen auf Beispielrouten und fiktiven Likes. Im Echtbetrieb zählt tatsächliche Aktivität.|Ces 10 lieux reposent sur les itinéraires et appréciations fictifs. Le classement réel suivra l’activité réelle.|تستند هذه الأماكن العشرة إلى مسارات وإعجابات افتراضية. سيعكس الترتيب الفعلي التفاعل الحقيقي.
profile|Gezi çantam|My travel kit|Meine Reisetasche|Mon carnet de voyage|حقيبة رحلتي
traveler|Demo gezgin|Demo traveler|Demo-Reisender|Voyageur de démo|مسافر تجريبي
profileNote|Kayıt gerekmez. Beğeniler, paylaşımlar, talepler ve gezi çantan bu demo oturumuna aittir. Oturum erişimini kaybedersen başka cihazdan geri yüklenemez.|No registration. Likes, posts, requests and your travel kit belong to this demo session. They cannot be recovered on another device if session access is lost.|Keine Registrierung. Likes, Beiträge, Anfragen und Reisetasche gehören zu dieser Demo-Sitzung. Bei Verlust des Zugangs keine Wiederherstellung auf einem anderen Gerät.|Sans inscription. Vos essais et votre carnet appartiennent à cette session. Ils ne sont pas récupérables sur un autre appareil si l’accès est perdu.|لا تسجيل مطلوب. الإعجابات والمنشورات والطلبات والحقيبة تخص الجلسة الحالية، ولا يمكن استعادتها على جهاز آخر عند فقدان الوصول.
reset|Demo denemelerimi sil|Delete my demo activity|Meine Demo-Aktivität löschen|Effacer mes essais|حذف نشاطي التجريبي
resetNote|Bu oturumdaki paylaşım, fotoğraf, yorum, beğeni, talep ve gezi çantası kayıtların silinir. Ortak örnek içerikler ve cihazındaki kayıtlı gezi planları korunur.|Deletes this session’s posts, photos, comments, likes, requests and travel kit. Shared samples and locally saved trip plans are kept.|Löscht Beiträge, Fotos, Kommentare, Likes, Anfragen und Reisetasche dieser Sitzung. Gemeinsame Beispiele und lokale Reisepläne bleiben erhalten.|Supprime les publications, photos, commentaires, avis, demandes et carnet de cette session. Les exemples communs et voyages enregistrés localement restent.|يحذف منشورات وصور وتعليقات وإعجابات وطلبات وحقيبة الجلسة، مع إبقاء الأمثلة المشتركة والخطط المحفوظة على الجهاز.
favorites|Görmek istediklerim|Places to see|Meine Wunschorte|Lieux à voir|أماكن أرغب بزيارتها
favorite|Gezi çantama ekle|Save to my travel kit|In Reisetasche speichern|Garder dans mon carnet|إضافة إلى حقيبتي
saved|Gezi çantamda|In my travel kit|In meiner Reisetasche|Dans mon carnet|في حقيبتي
emptyFavorites|Bir rotanın duraklarındaki yer imi simgesine dokunarak görmek istediğin yerleri burada topla.|Tap the bookmark beside a route stop to collect places here.|Mit dem Lesezeichen neben einem Routenstopp sammeln Sie Wunschorte.|Touchez le signet d’une étape pour la garder ici.|اضغط علامة الحفظ بجوار المحطة لجمع الأماكن هنا.
checklist|Yola çıkmadan|Before you go|Vor der Abfahrt|Avant de partir|قبل الانطلاق
water|Su ve mevsime uygun giysi|Water and seasonal clothing|Wasser und passende Kleidung|Eau et vêtements adaptés|ماء وملابس مناسبة للموسم
power|Şarj ve taşınabilir pil|Charged phone and power bank|Geladenes Handy und Powerbank|Téléphone chargé et batterie|هاتف مشحون وبطارية متنقلة
shoes|Zemine uygun rahat ayakkabı|Comfortable shoes for the terrain|Passende bequeme Schuhe|Chaussures adaptées au terrain|حذاء مريح مناسب للأرض
weather|Hava ve yol durumunu kontrol ettim|Weather and road conditions checked|Wetter und Straßen geprüft|Météo et routes vérifiées|تحققت من الطقس والطرق
hours|Ziyaret saatlerini kaynağından doğruladım|Visiting hours checked at source|Besuchszeiten an der Quelle geprüft|Horaires confirmés à la source|تحققت من مواعيد الزيارة
offline|Rota ve adresleri çevrimdışı kaydettim|Route and addresses saved offline|Route und Adressen offline gespeichert|Itinéraire et adresses hors ligne|حفظت المسار والعناوين دون اتصال
booking|Gerekli randevu ve izinleri teyit ettim|Appointments and permissions confirmed|Termine und Erlaubnisse bestätigt|Rendez-vous et autorisations confirmés|أكدت المواعيد والتصاريح
respect|Atıklarımı taşıyacağım; yerel yaşama saygı|Carry out litter; respect local life|Abfall mitnehmen; lokales Leben achten|Emporter ses déchets ; respecter la vie locale|حمل النفايات واحترام الحياة المحلية
search|Rota adı veya tema ara|Search route or theme|Route oder Thema suchen|Chercher une route ou un thème|ابحث عن مسار أو موضوع
noResults|Bu seçimde rota bulunamadı. İlçe veya ulaşım tercihini değiştir.|No routes match. Change district or transport.|Keine passende Route. Bezirk oder Verkehrsmittel ändern.|Aucun résultat. Changez de district ou de transport.|لا توجد نتائج. غيّر المقاطعة أو وسيلة النقل.
transport|Tüm ulaşım türleri|All transport modes|Alle Verkehrsmittel|Tous les transports|جميع وسائل النقل
how|Topluluğu nasıl deneyebilirim?|How can I try the community?|Wie teste ich die Community?|Comment essayer la communauté ?|كيف أجرب المجتمع؟
howText|Bir örnek rotayı aç; beğen, puan ver veya yorum yaz. “Rotayı bana uyarla” ile kendi planını oluştur. Planını kaydedip isim, fotoğraf ve video ekleyerek paylaşım akışını dene. Denemelerin sana özel kalır.|Open a sample, like, rate or comment. Adapt it into your own plan, save it and try adding a name, photos or video. Your trial activity stays private.|Beispiel öffnen, liken, bewerten oder kommentieren. Anpassen, speichern und mit Namen, Fotos oder Video ausprobieren. Versuche bleiben privat.|Ouvrez un exemple, aimez, notez ou commentez. Adaptez et enregistrez votre plan puis ajoutez nom, photos ou vidéo. Vos essais restent privés.|افتح مثالاً وأعجب به أو قيّمه أو علّق. عدّله لخطة خاصة واحفظها وأضف اسماً وصوراً أو فيديو. تبقى تجربتك خاصة.
ready|Demo hazırlanıyor…|Preparing your demo…|Demo wird vorbereitet…|Préparation de votre démo…|جارٍ إعداد العرض…
tryAgain|Demoya yeniden bağlan|Reconnect to demo|Demo erneut verbinden|Reconnecter la démo|إعادة الاتصال بالعرض
clear|Filtreleri temizle|Clear filters|Filter löschen|Effacer les filtres|مسح المرشحات`;
const map=Object.fromEntries(rows.split('\n').map(row=>{const [key,tr,en,de,fr,ar]=row.split('|');return [key,{tr,en,de,fr,ar}];}));
export const demoCopy=(locale:Locale):Record<string,string>=>Object.fromEntries(Object.entries(map).map(([k,v])=>[k,v[locale]]));
